What are we going to learn today?
In this article, we will learn sorting in Pandas data frame.Sorting means ordering the data in ascending and descending order.

Why is it important to learn?
Sorting makes data easy to comprehend. We gain quick insights and can tell better stories around our data with sorting. Data sets with scores and ratings especially benefit from sorting.

Later in the article, we will review the World Happiness Report data set. And we will use sorting to find answers to the following questions?

Find the country with the highest score
Find the country with the lowest social support
How are we going to achieve today’s learning goal?
Plan for today is:

Sort based on a single column
Sort based on multiple columns
Sort based on index
More sorting methods
Bonus Section

In [1]:
import pandas as pd

We will working on the StackOverflow 2020 annual developer dataset which can download from here. Now let’s read the data set and set the Respondent column as index using the index_col parameter.

In [2]:
df = pd.read_csv('../survey_results_public_2020.csv', index_col='Respondent')

In [3]:
df.head()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

Notice a lot of the values in the data set are NaN which means there is no value. We will remove the NaN values with dropna() method. This method is part of data cleaning and we will learn more about it in the future.

In [4]:
df.dropna(inplace=True)

Sort based on a single column
The sort_values() method is used to arrange the data along their axis (columns or rows) in the Pandas data frame.

Sort_values() method parameters:

by: It takes a single column or list of columns to sort by.
ascending: By default, set to True. If we want to sort in — descending, we set ascending as equal to False.
kind: This parameter takes a sorting algorithm. By default, ‘quicksort’ is set. However, we can change to ‘mergesort’ and ‘heapsort’. Quicksort is the fastest. Merge sort and Heap sort are both efficient for larger data sets. Merge sort is a little quicker but requires mode memory.
inplace: By default, set to False. When set to True, it applies changes in our original data frame.
Let’s sort our data by country column.

In [5]:
df.sort_values(by = 'Country')

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
17228,I am a developer by profession,No,37.0,18,Monthly,220000.0,23316.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot less welcome now than last year,40.0,19,14
45079,I am a developer by profession,Yes,26.0,15,Monthly,300000.0,31788.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",React.js,Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,40.0,10,6
10647,I am a developer by profession,Yes,38.0,13,Monthly,2000.0,25944.0,Albania,European Euro,EUR,...,Easy,Too long,No,"Another engineering discipline (such as civil,...",ASP.NET Core;Express;Vue.js,jQuery;Laravel;Vue.js,Somewhat less welcome now than last year,60.0,20,20
10098,I am a developer by profession,Yes,29.0,18,Monthly,130000.0,12912.0,Algeria,Algerian dinar,DZD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask;Laravel;Vue.js,jQuery;Laravel;Vue.js,Just as welcome now as I felt last year,40.0,11,5
62676,I am a developer by profession,Yes,27.0,16,Yearly,120000.0,993.0,Algeria,Algerian dinar,DZD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Flask;React.js;Vue.js,Angular;Express;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,50.0,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30291,I am a developer by profession,Yes,36.0,33,Monthly,45000000.0,23292.0,Viet Nam,Vietnamese dong,VND,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",Gatsby;React.js,Express;Gatsby;React.js,Just as welcome now as I felt last year,40.0,3,2
32962,I am a developer by profession,Yes,24.0,12,Monthly,8000000.0,4140.0,Viet Nam,Vietnamese dong,VND,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Vue.js,ASP.NET;Drupal;jQuery,Somewhat more welcome now than last year,40.0,10,2
20699,I am a developer by profession,Yes,27.0,14,Monthly,3000.0,36000.0,Viet Nam,United States dollar,USD,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",Express;Flask;React.js;Spring,Angular;Angular.js;Express;Flask;jQuery;Larave...,A lot more welcome now than last year,40.0,12,5
56632,I am a developer by profession,Yes,31.0,20,Monthly,24000.0,19632.0,Zambia,Zambian kwacha,ZMW,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Laravel;React.js;Vue.js,jQuery;Laravel;Vue.js,A lot less welcome now than last year,63.0,10,7
24779,I am a developer by profession,Yes,27.0,19,Monthly,2500.0,30000.0,Zimbabwe,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular;Angular.js;Express;Spring,Angular;Angular.js;Express;Spring,Just as welcome now as I felt last year,36.0,8,6

Notice the Country column has been sorted. Now lets do a Country column descending sort.

In [6]:
df.sort_values(by = 'Country', ascending=False)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
24779,I am a developer by profession,Yes,27.0,19,Monthly,2.500000e+03,30000.0,Zimbabwe,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular;Angular.js;Express;Spring,Angular;Angular.js;Express;Spring,Just as welcome now as I felt last year,36.0,8,6
56632,I am a developer by profession,Yes,31.0,20,Monthly,2.400000e+04,19632.0,Zambia,Zambian kwacha,ZMW,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Laravel;React.js;Vue.js,jQuery;Laravel;Vue.js,A lot less welcome now than last year,63.0,10,7
20167,I am a developer by profession,Yes,35.0,17,Yearly,1.900000e+09,81936.0,Viet Nam,Vietnamese dong,VND,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET;ASP.NET Core;Django;Express;Fl...,Angular;ASP.NET;ASP.NET Core;Express;jQuery;Re...,A lot more welcome now than last year,40.0,15,12
20699,I am a developer by profession,Yes,27.0,14,Monthly,3.000000e+03,36000.0,Viet Nam,United States dollar,USD,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",Express;Flask;React.js;Spring,Angular;Angular.js;Express;Flask;jQuery;Larave...,A lot more welcome now than last year,40.0,12,5
30291,I am a developer by profession,Yes,36.0,33,Monthly,4.500000e+07,23292.0,Viet Nam,Vietnamese dong,VND,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",Gatsby;React.js,Express;Gatsby;React.js,Just as welcome now as I felt last year,40.0,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62676,I am a developer by profession,Yes,27.0,16,Yearly,1.200000e+05,993.0,Algeria,Algerian dinar,DZD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Flask;React.js;Vue.js,Angular;Express;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,50.0,6,3
10098,I am a developer by profession,Yes,29.0,18,Monthly,1.300000e+05,12912.0,Algeria,Algerian dinar,DZD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask;Laravel;Vue.js,jQuery;Laravel;Vue.js,Just as welcome now as I felt last year,40.0,11,5
10647,I am a developer by profession,Yes,38.0,13,Monthly,2.000000e+03,25944.0,Albania,European Euro,EUR,...,Easy,Too long,No,"Another engineering discipline (such as civil,...",ASP.NET Core;Express;Vue.js,jQuery;Laravel;Vue.js,Somewhat less welcome now than last year,60.0,20,20
17228,I am a developer by profession,No,37.0,18,Monthly,2.200000e+05,23316.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot less welcome now than last year,40.0,19,14
45079,I am a developer by profession,Yes,26.0,15,Monthly,3.000000e+05,31788.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",React.js,Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,40.0,10,6

Sort based on multiple columns
So far, we have sorted our data based on a single column, but Pandas allows us to sort based on multiple columns.

It can be done with the sort_values() method, but we pass the list of columns.

Here we sort our data bytwo columns Country and ConvertedComp. First, it sort by Country column with ascending order, and then the ConvertedComp column.

In [7]:
df.sort_values(by = ['Country', 'ConvertedComp'])

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
17228,I am a developer by profession,No,37.0,18,Monthly,2.200000e+05,23316.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot less welcome now than last year,40.0,19,14
10647,I am a developer by profession,Yes,38.0,13,Monthly,2.000000e+03,25944.0,Albania,European Euro,EUR,...,Easy,Too long,No,"Another engineering discipline (such as civil,...",ASP.NET Core;Express;Vue.js,jQuery;Laravel;Vue.js,Somewhat less welcome now than last year,60.0,20,20
45079,I am a developer by profession,Yes,26.0,15,Monthly,3.000000e+05,31788.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",React.js,Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,40.0,10,6
62676,I am a developer by profession,Yes,27.0,16,Yearly,1.200000e+05,993.0,Algeria,Algerian dinar,DZD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Flask;React.js;Vue.js,Angular;Express;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,50.0,6,3
10098,I am a developer by profession,Yes,29.0,18,Monthly,1.300000e+05,12912.0,Algeria,Algerian dinar,DZD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask;Laravel;Vue.js,jQuery;Laravel;Vue.js,Just as welcome now as I felt last year,40.0,11,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20699,I am a developer by profession,Yes,27.0,14,Monthly,3.000000e+03,36000.0,Viet Nam,United States dollar,USD,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",Express;Flask;React.js;Spring,Angular;Angular.js;Express;Flask;jQuery;Larave...,A lot more welcome now than last year,40.0,12,5
20173,I am a developer by profession,Yes,32.0,14,Monthly,1.000000e+08,51744.0,Viet Nam,Vietnamese dong,VND,...,Easy,Appropriate in length,No,"A natural science (such as biology, chemistry,...",Express;React.js;Vue.js,Express;Vue.js,Somewhat less welcome now than last year,40.0,18,2
20167,I am a developer by profession,Yes,35.0,17,Yearly,1.900000e+09,81936.0,Viet Nam,Vietnamese dong,VND,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET;ASP.NET Core;Django;Express;Fl...,Angular;ASP.NET;ASP.NET Core;Express;jQuery;Re...,A lot more welcome now than last year,40.0,15,12
56632,I am a developer by profession,Yes,31.0,20,Monthly,2.400000e+04,19632.0,Zambia,Zambian kwacha,ZMW,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Laravel;React.js;Vue.js,jQuery;Laravel;Vue.js,A lot less welcome now than last year,63.0,10,7
24779,I am a developer by profession,Yes,27.0,19,Monthly,2.500000e+03,30000.0,Zimbabwe,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular;Angular.js;Express;Spring,Angular;Angular.js;Express;Spring,Just as welcome now as I felt last year,36.0,8,6

Notice Country columns is sort in the ascending order and the ConvertedComp column is also in ascending order with respect to Country column.

By default, both columns are sorted in ascending order, but we can change the order of both by passing a list of boolean operators in ascending parameters.

Lets sort the Country column is sorted by ascending order, and ConvertedComp is by descending order.

In [8]:
df.sort_values(by = ['Country', 'ConvertedComp'], ascending = [True, False])

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
45079,I am a developer by profession,Yes,26.0,15,Monthly,300000.0,31788.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",React.js,Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,40.0,10,6
10647,I am a developer by profession,Yes,38.0,13,Monthly,2000.0,25944.0,Albania,European Euro,EUR,...,Easy,Too long,No,"Another engineering discipline (such as civil,...",ASP.NET Core;Express;Vue.js,jQuery;Laravel;Vue.js,Somewhat less welcome now than last year,60.0,20,20
17228,I am a developer by profession,No,37.0,18,Monthly,220000.0,23316.0,Albania,Albanian lek,ALL,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Spring,Angular;Spring,A lot less welcome now than last year,40.0,19,14
10098,I am a developer by profession,Yes,29.0,18,Monthly,130000.0,12912.0,Algeria,Algerian dinar,DZD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask;Laravel;Vue.js,jQuery;Laravel;Vue.js,Just as welcome now as I felt last year,40.0,11,5
62676,I am a developer by profession,Yes,27.0,16,Yearly,120000.0,993.0,Algeria,Algerian dinar,DZD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Flask;React.js;Vue.js,Angular;Express;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,50.0,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30291,I am a developer by profession,Yes,36.0,33,Monthly,45000000.0,23292.0,Viet Nam,Vietnamese dong,VND,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",Gatsby;React.js,Express;Gatsby;React.js,Just as welcome now as I felt last year,40.0,3,2
15439,I am a developer by profession,Yes,33.0,17,Monthly,25000000.0,12936.0,Viet Nam,Vietnamese dong,VND,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",React.js,React.js,Somewhat less welcome now than last year,50.0,13,8
32962,I am a developer by profession,Yes,24.0,12,Monthly,8000000.0,4140.0,Viet Nam,Vietnamese dong,VND,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Vue.js,ASP.NET;Drupal;jQuery,Somewhat more welcome now than last year,40.0,10,2
56632,I am a developer by profession,Yes,31.0,20,Monthly,24000.0,19632.0,Zambia,Zambian kwacha,ZMW,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Laravel;React.js;Vue.js,jQuery;Laravel;Vue.js,A lot less welcome now than last year,63.0,10,7
24779,I am a developer by profession,Yes,27.0,19,Monthly,2500.0,30000.0,Zimbabwe,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular;Angular.js;Express;Spring,Angular;Angular.js;Express;Spring,Just as welcome now as I felt last year,36.0,8,6

Sort based on index
We can sort indexes (rows or columns) with the sort_index() method. This method is used to sort data by index labels. By default, it sorts by rows, but when the axis parameter is set to 1 (axis = 1), it sort by columns.

In [9]:
df.sort_index()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
33,I am a developer by profession,Yes,39.0,14,Monthly,4900.0,63564.0,Belgium,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js;Ruby on Rails,Angular;Angular.js;Django;Express;React.js,Just as welcome now as I felt last year,40.0,20,14
42,I am a developer by profession,No,32.0,14,Yearly,130000.0,130000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Spring,ASP.NET;Flask;React.js;Spring,Somewhat less welcome now than last year,37.0,16,10
47,I am a developer by profession,Yes,53.0,10,Yearly,58000.0,74970.0,United Kingdom,Pound sterling,GBP,...,Neither easy nor difficult,Appropriate in length,No,"A natural science (such as biology, chemistry,...",Flask;Spring,Flask;Spring,Just as welcome now as I felt last year,40.0,43,28
69,I am a developer by profession,Yes,25.0,12,Yearly,550000.0,594539.0,France,European Euro,EUR,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Flask,Django;Flask,Just as welcome now as I felt last year,40.0,13,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62863,I am a developer by profession,Yes,30.0,11,Yearly,230000.0,230000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular;Express;React.js,Express;React.js,Just as welcome now as I felt last year,40.0,10,7
62886,I am a developer by profession,Yes,32.0,24,Yearly,102700.0,102700.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular,Angular;Angular.js;ASP.NET Core,Somewhat more welcome now than last year,45.0,7,5
62904,I am a developer by profession,Yes,33.0,24,Yearly,95000.0,95000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,50.0,9,7
63288,I am a developer by profession,No,31.0,16,Yearly,65000.0,84019.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Express,Angular;Angular.js;Express,Just as welcome now as I felt last year,40.0,14,7
64938,I am a developer by profession,No,33.0,13,Yearly,55000.0,59454.0,France,European Euro,EUR,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Django;Flask;jQuery;Ruby on Rails,Just as welcome now as I felt last year,40.0,20,12

To sort in descending order

In [10]:
df.sort_index(ascending=False)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
64938,I am a developer by profession,No,33.0,13,Yearly,55000.0,59454.0,France,European Euro,EUR,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Django;Flask;jQuery;Ruby on Rails,Just as welcome now as I felt last year,40.0,20,12
63288,I am a developer by profession,No,31.0,16,Yearly,65000.0,84019.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Express,Angular;Angular.js;Express,Just as welcome now as I felt last year,40.0,14,7
62904,I am a developer by profession,Yes,33.0,24,Yearly,95000.0,95000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,50.0,9,7
62886,I am a developer by profession,Yes,32.0,24,Yearly,102700.0,102700.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular,Angular;Angular.js;ASP.NET Core,Somewhat more welcome now than last year,45.0,7,5
62863,I am a developer by profession,Yes,30.0,11,Yearly,230000.0,230000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular;Express;React.js,Express;React.js,Just as welcome now as I felt last year,40.0,10,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,I am a developer by profession,Yes,25.0,12,Yearly,550000.0,594539.0,France,European Euro,EUR,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Flask,Django;Flask,Just as welcome now as I felt last year,40.0,13,3
47,I am a developer by profession,Yes,53.0,10,Yearly,58000.0,74970.0,United Kingdom,Pound sterling,GBP,...,Neither easy nor difficult,Appropriate in length,No,"A natural science (such as biology, chemistry,...",Flask;Spring,Flask;Spring,Just as welcome now as I felt last year,40.0,43,28
42,I am a developer by profession,No,32.0,14,Yearly,130000.0,130000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Spring,ASP.NET;Flask;React.js;Spring,Somewhat less welcome now than last year,37.0,16,10
33,I am a developer by profession,Yes,39.0,14,Monthly,4900.0,63564.0,Belgium,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js;Ruby on Rails,Angular;Angular.js;Django;Express;React.js,Just as welcome now as I felt last year,40.0,20,14
10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4

We can also sort column names in order.

In [11]:
df.sort_index(axis='columns')

,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
10,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,Microsoft SQL Server,Microsoft SQL Server,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
33,39.0,14,Monthly,4900.0,63564.0,Belgium,European Euro,EUR,MongoDB,MongoDB;MySQL;PostgreSQL;SQLite,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Gatsby;React.js;Ruby on Rails,Angular;Angular.js;Django;Express;React.js,Just as welcome now as I felt last year,40.0,20,14
42,32.0,14,Yearly,130000.0,130000.0,United States,United States dollar,USD,Cassandra;DynamoDB;MongoDB,Microsoft SQL Server;MySQL;Oracle;Redis,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Spring,ASP.NET;Flask;React.js;Spring,Somewhat less welcome now than last year,37.0,16,10
47,53.0,10,Yearly,58000.0,74970.0,United Kingdom,Pound sterling,GBP,PostgreSQL;SQLite,Microsoft SQL Server;Oracle;PostgreSQL;SQLite,...,Neither easy nor difficult,Appropriate in length,No,"A natural science (such as biology, chemistry,...",Flask;Spring,Flask;Spring,Just as welcome now as I felt last year,40.0,43,28
69,25.0,12,Yearly,550000.0,594539.0,France,European Euro,EUR,PostgreSQL,MongoDB,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Flask,Django;Flask,Just as welcome now as I felt last year,40.0,13,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62863,30.0,11,Yearly,230000.0,230000.0,United States,United States dollar,USD,MongoDB;PostgreSQL;Redis,MongoDB;PostgreSQL;Redis,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular;Express;React.js,Express;React.js,Just as welcome now as I felt last year,40.0,10,7
62886,32.0,24,Yearly,102700.0,102700.0,United States,United States dollar,USD,Redis,Microsoft SQL Server;Redis,...,Easy,Appropriate in length,No,"Information systems, information technology, o...",Angular,Angular;Angular.js;ASP.NET Core,Somewhat more welcome now than last year,45.0,7,5
62904,33.0,24,Yearly,95000.0,95000.0,United States,United States dollar,USD,MongoDB;PostgreSQL,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Express;React.js,Express;Laravel;React.js;Vue.js,Just as welcome now as I felt last year,50.0,9,7
63288,31.0,16,Yearly,65000.0,84019.0,United Kingdom,Pound sterling,GBP,MongoDB,MongoDB,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Express,Angular;Angular.js;Express,Just as welcome now as I felt last year,40.0,14,7
64938,33.0,13,Yearly,55000.0,59454.0,France,European Euro,EUR,Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Elasticsearch;MongoDB;MySQL;Oracle;Po...,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Flask,Django;Flask;jQuery;Ruby on Rails,Just as welcome now as I felt last year,40.0,20,12

More Sorting methods
nlargest(): The nlargest() method returns the first n largest values in descending order. Where n is the number we give.

nsmallest(): The nsmallestt() method returns the first n smallest values in ascending order. Where n is the number we give..

These methods can be used with either series or data frame. Let’s use these methods practically.

Lets see the first 10 largest values of ConvertedComp column.

In [12]:
df['ConvertedComp'].nlargest(10)

Respondent
123     2000000.0
986     2000000.0
1128    2000000.0
1296    2000000.0
1345    2000000.0
3072    2000000.0
3179    2000000.0
4027    2000000.0
4125    2000000.0
5185    2000000.0
Name: ConvertedComp, dtype: float64

Now if we want to see the rows that correspond to the first 10 largest values of Age column.

In [13]:
df.nlargest(10, 'Age')

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
9726,"I am not primarily a developer, but I write co...",Yes,70.0,21,Monthly,150000.0,28308.0,Russian Federation,Russian ruble,RUB,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET;ASP.NET Core;jQuery,Angular;ASP.NET;ASP.NET Core;jQuery,A lot more welcome now than last year,35.0,50,30
5547,I am a developer by profession,Yes,66.0,13,Monthly,4000.0,48000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"A natural science (such as biology, chemistry,...",ASP.NET;ASP.NET Core;Express;React.js,ASP.NET;Express;jQuery,Just as welcome now as I felt last year,20.0,More than 50 years,44
1421,I am a developer by profession,Yes,63.0,20,Yearly,180000.0,180000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Express;Flask;jQuery;React.js;Symfony,Express;Flask;jQuery;React.js,Just as welcome now as I felt last year,40.0,42,35
47095,I am a developer by profession,No,63.0,32,Yearly,50000.0,64630.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core;jQuery;Vue.js,Angular.js;ASP.NET;ASP.NET Core;jQuery;Vue.js,Just as welcome now as I felt last year,38.0,30,25
20675,I am a developer by profession,Yes,61.0,12,Yearly,110000.0,110000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core;React.js,ASP.NET;jQuery;React.js,Just as welcome now as I felt last year,45.0,40,33
54376,I am a developer by profession,No,61.0,16,Yearly,175000.0,175000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,Express;React.js;Spring,Express;React.js,Just as welcome now as I felt last year,40.0,40,33
11712,I am a developer by profession,No,60.0,23,Yearly,750000.0,80922.0,Norway,Norwegian krone,NOK,...,Neither easy nor difficult,Appropriate in length,No,"Another engineering discipline (such as civil,...",Angular;ASP.NET Core,Angular;ASP.NET;ASP.NET Core;jQuery,Just as welcome now as I felt last year,37.0,35,30
60667,I am a developer by profession,No,60.0,20,Yearly,720000.0,77685.0,Norway,Norwegian krone,NOK,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",Angular;ASP.NET Core,Angular;ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,38.0,40,40
2008,I am a developer by profession,No,59.0,16,Yearly,104000.0,104000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"A business discipline (such as accounting, fin...",ASP.NET;ASP.NET Core,ASP.NET,Just as welcome now as I felt last year,40.0,41,36
4152,I am a developer by profession,Yes,59.0,16,Yearly,125000.0,125000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery,jQuery,Just as welcome now as I felt last year,40.0,44,37

Similarly let see the 10 smallest values of Age column

In [14]:
df['Age'].nsmallest(10)

Respondent
32644    17.0
15311    18.0
17825    18.0
50077    18.0
2373     19.0
10114    19.0
10651    19.0
13461    19.0
13704    19.0
15436    19.0
Name: Age, dtype: float64