In [2]:
import pandas as pd

First, we will see a simple data set created from a dictionary with the Data Frame function.

In [3]:
people = {
"Id": ['cs-01', 'mth-02', 'eng-03', 'phy-04', 'mth-05', 'cs-06'],
"Name": ["Fatima", 'Noureen', 'Salman', 'Sana', 'Jack', 'Ali'],
"subject": ['computer science', 'math', 'english', 'physics', 'statistics', 'programming']
}
data = pd.DataFrame(people)
data

       Id     Name           subject
0   cs-01   Fatima  computer science
1  mth-02  Noureen              math
2  eng-03   Salman           english
3  phy-04     Sana           physics
4  mth-05     Jack        statistics
5   cs-06      Ali       programming

Let us review the output of the data (data frame), and we have three columns (Id, Name, subject) and six rows with default index number range(0,1,2,3,….n).

Set custom indexes
Set index method

The set index method is used to set existing columns as the data frame index. Let’s go ahead and make the Id column an index. If we try to access Id like a column (df[‘Id’]), it will show an error. Because once we have set Id as an index, it is no longer a column.

The change of the id column to the index is only temporary, and if we want to make it permanent, we will use inplace=True. This will permanently change our data set.

In [4]:
data.set_index('Id', inplace=True)
data

           Name           subject
Id
cs-01    Fatima  computer science
mth-02  Noureen              math
eng-03   Salman           english
phy-04     Sana           physics
mth-05     Jack        statistics
cs-06       Ali       programming

Observe our index is not the Id column and not numbers anymore.

View index method
dataframe.index method is used to view the index of a data frame.It is a quick and easy way to look at the index of a data frame.

In [7]:
data.index

Index(['cs-01', 'mth-02', 'eng-03', 'phy-04', 'mth-05', 'cs-06'], dtype='object', name='Id')

Index is Id column as expected, and we can access them with the loc function (discussed here), which is very easy and make more sense than default indexes (0,1,2,3…n).

In [9]:
data.loc['cs-01']

Name                 Fatima
subject    computer science
Name: cs-01, dtype: object

Resetting index
Reset index method

The reset_index() method resets the indexes of the data frame and reverts it to the default.

Lets try this method.

In [10]:
data.reset_index(inplace=True)
data

       Id     Name           subject
0   cs-01   Fatima  computer science
1  mth-02  Noureen              math
2  eng-03   Salman           english
3  phy-04     Sana           physics
4  mth-05     Jack        statistics
5   cs-06      Ali       programming

Observe Id is now added back as a column.

Set a column as an index
Another method, we can set a custom index with the index_col parameter direct from where we read the data set. Let us see how we can do this with a real-world data set called Stack Overflow Annual Developer Survey. You can download the data set here.

Let’s set the Country column as the index

In [11]:
df = pd.read_csv('../survey_results_public_2020.csv', index_col='Country')
df.head()

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Country,,,,,,,,,,,,,,,,,,,,,
Germany,1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
United Kingdom,2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
Russian Federation,3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
Albania,4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
United States,5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

Observe Country column is now the index.

Index sorting
Sort index method

We can also sort the indexes by axis the sort_index method. By axis mean either we can sort row labels or column labels.

Set axis = 0 to sorts the row labels and axis = 1 for columns. Instead of using axis = 0 or axis = 1 we can also use axis = ‘rows’ or axis = ‘columns’ respectively. If we do not mention an axis it sorts rows index by default.

Ascending order is default. To sort in descending order, we set ascending parameter to False (ascending = False)

As discussed earlier, if we want to change the original data frame, we enable an in place argument by inplace=True.

Let’s sort our row index by descending order.

In [12]:
df.sort_index(ascending=False)

,Respondent,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Country,,,,,,,,,,,,,,,,,,,,,
Zimbabwe,9156,I am a developer by profession,No,29.0,21,Monthly,NaN,NaN,United States dollar,USD,...,Easy,Too long,No,"Information systems, information technology, o...",Angular,Angular;ASP.NET;Flask;jQuery,Just as welcome now as I felt last year,35.0,7,4
Zimbabwe,25843,"I am not primarily a developer, but I write co...",Yes,30.0,20,Monthly,360.0,4320.0,United States dollar,USD,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",ASP.NET;ASP.NET Core,Flask;Laravel,Just as welcome now as I felt last year,44.0,7,2
Zimbabwe,24513,I am a developer by profession,Yes,21.0,15,Weekly,NaN,NaN,United States dollar,USD,...,Neither easy nor difficult,Too long,No,NaN,Angular.js;Express;jQuery;Laravel;React.js,jQuery,A lot more welcome now than last year,NaN,7,3
Zimbabwe,55609,I am a student who is learning to code,No,19.0,17,NaN,NaN,NaN,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Django,Django,Just as welcome now as I felt last year,NaN,2,NaN
Zimbabwe,17220,I am a student who is learning to code,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Easy,Appropriate in length,No,"A business discipline (such as accounting, fin...",Angular.js;Django;Flask;Gatsby;jQuery;React.js...,Angular.js;Django;jQuery;React.js;Vue.js,Not applicable - I did not use Stack Overflow ...,NaN,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,60055,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,61121,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,61570,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,61918,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,62605,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now let’s sort our columns in descending order

In [13]:
df.sort_index(ascending=False, axis='columns')

,YearsCodePro,YearsCode,WorkWeekHrs,WelcomeChange,WebframeWorkedWith,WebframeDesireNextYear,UndergradMajor,Trans,SurveyLength,SurveyEase,...,DevType,DatabaseWorkedWith,DatabaseDesireNextYear,CurrencySymbol,CurrencyDesc,ConvertedComp,CompTotal,CompFreq,Age1stCode,Age
Country,,,,,,,,,,,,,,,,,,,,,
Germany,27,36,50.0,Just as welcome now as I felt last year,ASP.NET;ASP.NET Core,ASP.NET Core,"Computer science, computer engineering, or sof...",No,Appropriate in length,Neither easy nor difficult,...,"Developer, desktop or enterprise applications;...",Elasticsearch;Microsoft SQL Server;Oracle,Microsoft SQL Server,EUR,European Euro,NaN,NaN,Monthly,13,NaN
United Kingdom,4,7,NaN,Somewhat more welcome now than last year,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,...,"Developer, full-stack;Developer, mobile",NaN,NaN,GBP,Pound sterling,NaN,NaN,NaN,19,NaN
Russian Federation,NaN,4,NaN,Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,NaN
Albania,4,7,40.0,Somewhat less welcome now than last year,NaN,NaN,"Computer science, computer engineering, or sof...",No,NaN,NaN,...,NaN,NaN,NaN,ALL,Albanian lek,NaN,NaN,NaN,18,25.0
United States,8,15,NaN,Just as welcome now as I felt last year,Ruby on Rails,Django;Ruby on Rails,"Computer science, computer engineering, or sof...",No,Too short,Easy,...,NaN,MySQL;PostgreSQL;Redis;SQLite,MySQL;PostgreSQL,NaN,NaN,NaN,NaN,NaN,16,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
United States,Less than 1 year,10,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,...,Senior executive/VP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN
Morocco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Viet Nam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Poland,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,...,NaN,Oracle,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Spain,NaN,NaN,NaN,NaN,Angular;Angular.js;ASP.NET Core;jQuery,ASP.NET Core;jQuery,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,...,NaN,MariaDB;Microsoft SQL Server;MySQL;Oracle,MariaDB;Microsoft SQL Server,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In the above output, you can see that our first column is YearsCodePro and not Respondent anymore.