What are we going to learn today?
In this article, we will learn to update and substitute the values in Pandas data frames.

Why is it important to learn?
Often real-world data sets are not conducive to analysis, for example — Incorrect values, syntax, and mistakenly inserted records. That’s why updating rows and columns are necessary to learn to make our data analysis easy.

We will see an example of students marks and update a column with Pass or Fail when the data values meet passing marks threshold criteria.

How are we going to achieve today’s learning goal?
Plan for today is:

Updating column names
Updating rows
Updating rows based on conditions

In [1]:
import pandas as pd

We will create a data frame with the help of a dictionary.

In [2]:
Student = {
"Id": ['cs-01', 'mth-02', 'eng-03', 'phy-04', 'mth-05', 'cs-06'],
"Name": ["Fatima Khan", 'Noureen Ali', 'Salman Aslam', 'Sana Khan', 'Adam Jack', 'Ali Khan'],
"subject": ['computer science', 'math', 'english', 'physics', 'statistics', 'programming'],
"marks": [45, 90, 60, 37, 49, 50]
}
data = pd.DataFrame(Student)
data

       Id          Name           subject  marks
0   cs-01   Fatima Khan  computer science     45
1  mth-02   Noureen Ali              math     90
2  eng-03  Salman Aslam           english     60
3  phy-04     Sana Khan           physics     37
4  mth-05     Adam Jack        statistics     49
5   cs-06      Ali Khan       programming     50

Updating column names
The rename method is used to alter the names of the columns in the data set. It takes the columns parameter, and we will assign a dictionary to this parameter, where the dictionary’s key is the old column name, and the value will be the new column name.

Let’s change the Name column into Full Name as it is more appropriate. And to make the change permanent, we will set the inplace parameter to True. By default, it is set to False.

In [3]:
data.rename(columns = {'Name': 'Full Name'})

       Id     Full Name           subject  marks
0   cs-01   Fatima Khan  computer science     45
1  mth-02   Noureen Ali              math     90
2  eng-03  Salman Aslam           english     60
3  phy-04     Sana Khan           physics     37
4  mth-05     Adam Jack        statistics     49
5   cs-06      Ali Khan       programming     50

Now, we will change all the column names into the lower case, which will make it easy to select columns. We will use the columns.lower() method with string class (str class). Without using the string class we will get an error.

In [4]:
data.columns = data.columns.str.lower()
data

       id          name           subject  marks
0   cs-01   Fatima Khan  computer science     45
1  mth-02   Noureen Ali              math     90
2  eng-03  Salman Aslam           english     60
3  phy-04     Sana Khan           physics     37
4  mth-05     Adam Jack        statistics     49
5   cs-06      Ali Khan       programming     50

Updating Rows
Now let’s update a row. First, let’s select row number four.

In [5]:
data.loc[4]

id             mth-05
name        Adam Jack
subject    statistics
marks              49
Name: 4, dtype: object

Now we will create a list with the new row values and assign it to row 4.

In [7]:
data.loc[4] = ['cs-05', 'Ali', 'Database', 47]
data.loc[4]

id            cs-05
name            Ali
subject    Database
marks            47
Name: 4, dtype: object

We can see the output that the row has been updated. Very easy.

What if we wanted to update a few values, not a complete row. We can achieve it by selecting only the values we want to edit. To update the name and subject in row 0, we will select it first.

In [8]:
data.loc[0, ['name', 'subject']]

name            Fatima Khan
subject    computer science
Name: 0, dtype: object

We assign two new values by selecting row 0 with the name and subject columns.

In [10]:
data.loc[0, ['name', 'subject']] = ['Farhan', 'Python']
data.loc[0]

id          cs-01
name       Farhan
subject    Python
marks          45
Name: 0, dtype: object

Updating Rows based on conditions
Updating rows based on certain conditions is a widespread use case. We will update the marks column with a Fail string when the value is below 50.

First, let’s create a condition and assign it to a variable

In [11]:
filt = data['marks'] < 50
filt

0     True
1    False
2    False
3     True
4     True
5    False
Name: marks, dtype: bool

The output returns a boolean value. It returns True where the condition is matched and False where unmatched. To get the desired output, we will go to our trusty loc method and use the condition filter (filt) we created to update the marks column.

In [12]:
data.loc[filt, 'marks'] = 'Fail'
data

C:\Users\sergi\AppData\Local\Temp\ipykernel_27808\1385143333.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Fail' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[filt, 'marks'] = 'Fail'

       id          name      subject marks
0   cs-01        Farhan       Python  Fail
1  mth-02   Noureen Ali         math    90
2  eng-03  Salman Aslam      english    60
3  phy-04     Sana Khan      physics  Fail
4   cs-05           Ali     Database  Fail
5   cs-06      Ali Khan  programming    50

Awesome! Now, we can easily see who failed the test.