What are we going to learn today?
In this article, we will learn multi Indexing in Pandas. So far, we have seen data sets with one-level index, but in multi-level or advanced indexing, we have a hierarchy of indexes. We will learn different ways of creating and manipulating multi-index in Pandas.

Why is it important to learn?
Multi-level indexing provides granularity. It provides an easier, more accurate and faster way to filter and process information. For example, a football player can be referenced with a hierarchical index of (Country, State, Ranking).

Multi indexing is an excellent way to analyze and manipulate sophisticated data, especially working with higher dimensional data.

How can we going to achieve today’s learning goal?
Today’s learning plan is:

Series with multi-Index
Data frame with multi-Index
Reshaping a data frame
Sorting in multi-Index

In [1]:
import pandas as pd
import numpy as np

In [4]:
data = pd.Series( [56,78,99,56,88,59,100,57,91], index=[['Team1', 'Team1', 'Team1', 'Team2', 'Team2', 'Team2','Team3', 'Team3', 'Team3'],['player_1', 'player_2', 'player_3','player_1', 'player_2', 'player_3','player_1', 'player_2','player_3']],name="Player's Score")
data

Team1  player_1     56
       player_2     78
       player_3     99
Team2  player_1     56
       player_2     88
       player_3     59
Team3  player_1    100
       player_2     57
       player_3     91
Name: Player's Score, dtype: int64

Let’s review the output, and we can see that we have two indexes. The first index is called level 0 index and the 2nd index is level 1 index.

Now let’s view just the multi-index of the series.

In [5]:
data.index

MultiIndex([('Team1', 'player_1'),
            ('Team1', 'player_2'),
            ('Team1', 'player_3'),
            ('Team2', 'player_1'),
            ('Team2', 'player_2'),
            ('Team2', 'player_3'),
            ('Team3', 'player_1'),
            ('Team3', 'player_2'),
            ('Team3', 'player_3')],
           )

Let’s select a range by selecting level 0 index.

In [6]:
data['Team1' : 'Team2']

Team1  player_1    56
       player_2    78
       player_3    99
Team2  player_1    56
       player_2    88
       player_3    59
Name: Player's Score, dtype: int64

Multi-index behaves differently with the loc and iloc function. Level 0 is treated as a row and Level 1 is treated as a column.

For example, if we want to select all level 0 indexes but only index number 2 value of level 1 index. We can writethe code like this.

In [7]:
data.loc[:, 'player_1']

Team1     56
Team2     56
Team3    100
Name: Player's Score, dtype: int64

Here let’s select a specific value by supplying the exact indexs.

In [8]:
data.loc['Team1', 'player_2']

np.int64(78)

Data frame with Multi-Index
Now, we will see a multi-index in data frame. For that, we will create a small data frame with a dictionary.

In [9]:
df = {'name' :['Jack', 'Fatima', 'Salman', 'Sahil', 'Noureen', 'Hamza'],'rank' :[1, 2, 1, 2, 1, 2],'city' :['Khi', 'Khi', 'Isb', 'Isb', 'Lhr', 'Lhr'],'CS_rating' : [21, 56, 34, 45, 24, 34],'Maths_rating' : [76, 45, 56, 34, 234, 45]}
df = pd.DataFrame(df)
df

      name  rank city  CS_rating  Maths_rating
0     Jack     1  Khi         21            76
1   Fatima     2  Khi         56            45
2   Salman     1  Isb         34            56
3    Sahil     2  Isb         45            34
4  Noureen     1  Lhr         24           234
5    Hamza     2  Lhr         34            45

Now lets set the city and rank columns as multi index using the set_index method. Moreover, set the inplace parameter is set to True so our original data frame will be changed permanently.

In [10]:
df.set_index(['city', 'rank'], inplace=True)
df

              name  CS_rating  Maths_rating
city rank
Khi  1        Jack         21            76
     2      Fatima         56            45
Isb  1      Salman         34            56
     2       Sahil         45            34
Lhr  1     Noureen         24           234
     2       Hamza         34            45

And now we can see that our data has multi-index with city and rank as indexes.

In [11]:
df.index

MultiIndex([('Khi', 1),
            ('Khi', 2),
            ('Isb', 1),
            ('Isb', 2),
            ('Lhr', 1),
            ('Lhr', 2)],
           names=['city', 'rank'])

Let’s suppose we want the record stored at multi index Khi, whose rank is 1 using the loc method.

In [12]:
df.loc['Khi', 1]

name            Jack
CS_rating         21
Maths_rating      76
Name: (Khi, 1), dtype: object

Reshaping a data frame
When we have multi-index, we can use stack and unstack methods which returns a reshaped data frame.

unstack(): It returns a data frame similar to a pivot table in excel. It returns a new level of columns whose inner-most level consists of the pivoted index labels.

stack(): It returns a reshaped multi index Series.

Let’s review unstack() first.

In [13]:
df.unstack()

         name         CS_rating     Maths_rating
rank        1       2         1   2            1   2
city
Isb    Salman   Sahil        34  45           56  34
Khi      Jack  Fatima        21  56           76  45
Lhr   Noureen   Hamza        24  34          234  45

Let’s review the output, we have new column rank and row labels city. We can interpret the output that Salman’s rank is 1 and Sahil’s rank is 2. They are both from Isb, and Salman’s score_1 is 34, and Sahil’s score_1 is 45 same as score_2.

Now let’s review the stack() method.

In [14]:
df.stack()

city  rank
Khi   1     name               Jack
            CS_rating            21
            Maths_rating         76
      2     name             Fatima
            CS_rating            56
            Maths_rating         45
Isb   1     name             Salman
            CS_rating            34
            Maths_rating         56
      2     name              Sahil
            CS_rating            45
            Maths_rating         34
Lhr   1     name            Noureen
            CS_rating            24
            Maths_rating        234
      2     name              Hamza
            CS_rating            34
            Maths_rating         45
dtype: object

As discussed, stack()it returns a multi index series.

Sorting in Multi-Index
Index sorting is important in real life. We will use the sort_index() method with level parameter. In our case city is level 0 index and rank is level 1 index.

In [15]:
df.sort_index(level=0)

              name  CS_rating  Maths_rating
city rank
Isb  1      Salman         34            56
     2       Sahil         45            34
Khi  1        Jack         21            76
     2      Fatima         56            45
Lhr  1     Noureen         24           234
     2       Hamza         34            45

The city is on level 0, and the rank is on level 1.

In [16]:
df.sort_index(level=1)

              name  CS_rating  Maths_rating
city rank
Isb  1      Salman         34            56
Khi  1        Jack         21            76
Lhr  1     Noureen         24           234
Isb  2       Sahil         45            34
Khi  2      Fatima         56            45
Lhr  2       Hamza         34            45

The output shows that the city index is sorted in ascending order when the level is set to 0, and rank is sorted in ascending order when the level is set to 1.