What are we going to learn today?
In this article will learn some more data cleaning techniques.We will learn to change data types, fill missing values and remove duplicates. This process is called Casting.

For example if we want to take the mean of a column that apparently has numerical values. But instead we find that the numerical values have been saved as strings (text). We will have to change the data type from text to numerical for the Mean operation.

Pandas data types provide a mechanism to store a certain type of data. There are several data types but we will be working with numerical (interger, float) and text (string) data types.

How are we going to achieve today’s learning goal?
Plan for today is:

Casting data types
Interpolation Methods
Removing Duplicates

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../survey_results_public_2021.csv')

In [3]:
df.head()

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
1,2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
2,3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
3,4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
4,5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

The YearsCode column in the data set records the coding experience of developers in the number of years.

In [4]:
df.YearsCode

0        NaN
1          7
2        NaN
3        NaN
4         17
        ...
83434      6
83435      4
83436     10
83437      5
83438     14
Name: YearsCode, Length: 83439, dtype: object

Let’s try to find the average experience in the number of years for the developers in our survey.

In [5]:
df['YearsCode'].mean()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

We got an error.

Lets run the df.info() method and see the data type of column YearsCode column.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  object
 10  YearsCodePro                  61216 non-null  object
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompTotal                     47183 non-null  float64
 15  CompFreq                      52150 non-null  object
 16  LanguageHaveWorkedWith        82357 non-null  object
 17  LanguageWantToWorkWith        76821 non-null  object
 18  DatabaseHaveWorkedWith        69546 non-null  object
 19  DatabaseWantToWorkWith        58299 non-null  object
 20  PlatformHaveWorkedWith        52135 non-null  object
 21  PlatformWantToWorkWith        41619 non-null  object
 22  WebframeHaveWorkedWith        61707 non-null  object
 23  WebframeWantToWorkWith        52095 non-null  object
 24  MiscTechHaveWorkedWith        47055 non-null  object
 25  MiscTechWantToWorkWith        38021 non-null  object
 26  ToolsTechHaveWorkedWith       72537 non-null  object
 27  ToolsTechWantToWorkWith       65480 non-null  object
 28  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 29  NEWCollabToolsWantToWorkWith  73022 non-null  object
 30  OpSys                         83294 non-null  object
 31  NEWStuck                      83052 non-null  object
 32  NEWSOSites                    83171 non-null  object
 33  SOVisitFreq                   82413 non-null  object
 34  SOAccount                     82525 non-null  object
 35  SOPartFreq                    67553 non-null  object
 36  SOComm                        82319 non-null  object
 37  NEWOtherComms                 82828 non-null  object
 38  Age                           82407 non-null  object
 39  Gender                        82286 non-null  object
 40  Trans                         80678 non-null  object
 41  Sexuality                     73366 non-null  object
 42  Ethnicity                     79464 non-null  object
 43  Accessibility                 77603 non-null  object
 44  MentalHealth                  76920 non-null  object
 45  SurveyLength                  81711 non-null  object
 46  SurveyEase                    81948 non-null  object
 47  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), int64(1), object(45)
memory usage: 30.6+ MB

The output says object as the data type of YearsCode column, which is equivalent to a string object type. We must convert this column into a numerical data type integer or float (decimal numbers).

To convert the data type of the YearsCode column, we will use the astype() method.

In [7]:
df['YearsCode'].astype(float)

ValueError: could not convert string to float: 'Less than 1 year'

We are still getting an error. Let’s investigate more and look at the unique values in the YearsCode column.

In [8]:
df['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20', '8', '19', '5', 'Less than 1 year', '22',
       '2', '1', '34', '21', '13', '25', '24', '30', '31', '18', '38',
       'More than 50 years', '27', '41', '42', '35', '23', '28', '11',
       '37', '44', '43', '36', '33', '45', '29', '50', '46', '32', '47',
       '49', '48'], dtype=object)

The output reveals two text phrases that cannot be simply converted to numerical values. We will replace the phrases with numerical values of 0 and 55, respectively.

In [11]:
df['YearsCode'].replace({'Less than 1 year': 0, 'More than 50 years':55}, inplace=True)

Now let’s try to change the data type of the YearsCode column again.

In [13]:
df['YearsCode'] = df['YearsCode'].astype(float)

Success and no errors now.

Time to take the Mean of the YearsCode column, which will work perfectly now.

In [14]:
df['YearsCode'].mean()

np.float64(12.346529317377298)

Interpolation Methods
In statistics, interpolation is a method in which known values are used to estimate unknown values. Pandas, ffill and bfill methods for interpolation. ffill and bfill are sub-methods of the fillna() method, used to fill missing values.

ffill: ffill means forward to fill. It is used to forward fill the missing values present in the data set.

bfill: bfill means backward fill. It is used to backwards fill the missing values present in the data set.

Let’s create a custom data set with missing values. We will use the random function from the NumPy library and fill some NaN values using the iloc method.

In [15]:
data = pd.DataFrame(np.random.randn(7,3))
data

          0         1         2
0 -0.046329  0.836566 -0.033267
1 -0.360607 -1.936640 -1.585116
2 -1.578345  0.551983  0.011158
3 -1.135151  1.455874  0.251399
4 -0.365974 -0.647180 -0.738993
5 -0.377360  0.938398  1.694541
6  1.090654 -1.849106 -0.165636

Let’s sprinkle some NaN in the data set to simulate missing values.

In [16]:
data.iloc[:3, 1] = np.nan
data.iloc[:2, 2] = np.nan
data.iloc[4:6, 2] = np.nan
data

          0         1         2
0 -0.046329       NaN       NaN
1 -0.360607       NaN       NaN
2 -1.578345       NaN  0.011158
3 -1.135151  1.455874  0.251399
4 -0.365974 -0.647180       NaN
5 -0.377360  0.938398       NaN
6  1.090654 -1.849106 -0.165636

We will use the ffill method first to fill the missing values in the data set.

In [17]:
data.fillna(method='ffill')

C:\Users\sergi\AppData\Local\Temp\ipykernel_32024\1844443866.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

          0         1         2
0 -0.046329       NaN       NaN
1 -0.360607       NaN       NaN
2 -1.578345       NaN  0.011158
3 -1.135151  1.455874  0.251399
4 -0.365974 -0.647180  0.251399
5 -0.377360  0.938398  0.251399
6  1.090654 -1.849106 -0.165636

The output shows that rows 4 and 5 of column 2 have been filled with the value of row number 3 and column number 2. You might be wondering why we still have missing values in the data set. Go back to the definition of the ffil method, and you will see that it only forwards fills the values.

The backward fill method is as easy as the forward fill. Let’s see the data frame real quick.

In [18]:
data

          0         1         2
0 -0.046329       NaN       NaN
1 -0.360607       NaN       NaN
2 -1.578345       NaN  0.011158
3 -1.135151  1.455874  0.251399
4 -0.365974 -0.647180       NaN
5 -0.377360  0.938398       NaN
6  1.090654 -1.849106 -0.165636

Data frame is back to its original state.

Apply bfill.

In [19]:
data.fillna(method='bfill')

C:\Users\sergi\AppData\Local\Temp\ipykernel_32024\1397359497.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

          0         1         2
0 -0.046329  1.455874  0.011158
1 -0.360607  1.455874  0.011158
2 -1.578345  1.455874  0.011158
3 -1.135151  1.455874  0.251399
4 -0.365974 -0.647180 -0.165636
5 -0.377360  0.938398 -0.165636
6  1.090654 -1.849106 -0.165636

The output shows the missing values have been backwards filled.

We can also use a limit parameter with ffill and bfill methods. It controls the number of values the method would fill.

Let’s set the limit to 1 and use the ffill method.

In [20]:
data.fillna(method='ffill', limit=1)

C:\Users\sergi\AppData\Local\Temp\ipykernel_32024\985502726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', limit=1)

          0         1         2
0 -0.046329       NaN       NaN
1 -0.360607       NaN       NaN
2 -1.578345       NaN  0.011158
3 -1.135151  1.455874  0.251399
4 -0.365974 -0.647180  0.251399
5 -0.377360  0.938398       NaN
6  1.090654 -1.849106 -0.165636

The output shows that only row number 4 of column 2 is filled with the value.

Removing Duplicates
One of the main problems we get from duplicated data is data leakage. Removing duplicates isessential for high performing machine learning models and better data analysis.

We will use the duplicated() method to remove the duplicated records.

First, we will check our StackOverflow survey data set. We will create a custom dataset to understand the duplicated() method if we do not find any.

Let’s see how many duplicates we have in our data set.

In [21]:
df.duplicated().sum()

np.int64(0)

Since our existing data set has no duplicated we will create one with duplicates.

Creating a data frame from the dictionary.

In [22]:
data1 = pd.DataFrame({'col1': ['one', 'two'] * 4 + ['two'], 'col2': [1, 1, 2, 3, 3, 4, 4,5,5]})
data1

  col1  col2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4
6  one     4
7  two     5
8  two     5

Let’s check the duplicate records. At first, it returns boolean values.

In [23]:
data1.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
dtype: bool

We can get a count of duplicate values with the sum() method.

In [24]:
data1.duplicated().sum()

np.int64(1)

We have found 1 duplicate record. To remove duplicated records, drop_duplicates() methods are used. It also takes inplace parameters if we want to change in the original dataframe.

In [25]:
data1.drop_duplicates()

  col1  col2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4
6  one     4
7  two     5

We can see in the output that we got 7 rows instead of 8.