In [28]:
import pandas as pd
df= pd.read_csv('../Customers.csv')
df

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
0,1001,Grace,Mwende,123-456-7098,Female,True,26,True,'14/1/2023'
1,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
2,1003,Emis,Leonard,NaN,F,True,60,True,'16/1/2023'
3,1004,Olive,Cira,N/a,F,False,40,False,'17/1/2023'
4,1005,leornard..,Thirika,304-762-2467,Male,True,89,True,'17/1/2023'
5,1006,/ignatius,Micheni,123-543-2345,M,False,62,False,'19/1/2023'
6,1007,_Kevin,Nyaga,876|678|3469,Male,True,32,True,'20/1/2023'
7,1008,Francis,Njiru,NaN,M,False,78,False,NaN
8,1009,Joe,Ratemo,N/a,M,True,22,True,'22/1/2023'
9,1010,faith,Kathomi,N/a,Female,False,N/a,False,'23/1/2023'
10,1011,Lenny,Nyaga,N/a,M,True,31,True,'22/1/2023'
11,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
12,1004,Olive,Cira,N/a,F,False,30,False,'17/1/2023'

2. Check number of columns and rows by using the shape function

In [29]:
df.shape

(13, 9)

3. Check dataframe information- Provides a concise summary of our dataframe. we understand the column names and their data type,non-null values and memory usage

a. df.info()

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_id        13 non-null     int64
 1   Firstname          13 non-null     object
 2   LastName           13 non-null     object
 3   PhoneNumber        11 non-null     object
 4   Gender             13 non-null     object
 5   Other              13 non-null     bool
 6   age                13 non-null     object
 7   Not_Useful_column  13 non-null     bool
 8   Sale date          12 non-null     object
dtypes: bool(2), int64(1), object(6)
memory usage: 886.0+ bytes

b. You can also check the columns names only by

In [31]:
df.columns

Index(['Customer_id', 'Firstname', 'LastName', 'PhoneNumber', 'Gender',
       'Other', 'age', 'Not_Useful_column', 'Sale date'],
      dtype='object')

c. Also check the data type only by

In [32]:
df.dtypes

Customer_id           int64
Firstname            object
LastName             object
PhoneNumber          object
Gender               object
Other                  bool
age                  object
Not_Useful_column      bool
Sale date            object
dtype: object

4. Check info and statistics of numeric data eg count, mean,min,max etc by using the describe function

In [33]:
df.describe()

       Customer_id
count    13.000000
mean   1005.538462
std       3.256158
min    1001.000000
25%    1003.000000
50%    1005.000000
75%    1008.000000
max    1011.000000

5. Check some of the data by using the head and tail function- Head by default gives the first 5 rows and tail gives the last 5 rows
df.head() but if you put df.head(10) will give you 10 rows instead of 5 same as the tail

In [34]:
df.head(10)

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
0,1001,Grace,Mwende,123-456-7098,Female,True,26,True,'14/1/2023'
1,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
2,1003,Emis,Leonard,NaN,F,True,60,True,'16/1/2023'
3,1004,Olive,Cira,N/a,F,False,40,False,'17/1/2023'
4,1005,leornard..,Thirika,304-762-2467,Male,True,89,True,'17/1/2023'
5,1006,/ignatius,Micheni,123-543-2345,M,False,62,False,'19/1/2023'
6,1007,_Kevin,Nyaga,876|678|3469,Male,True,32,True,'20/1/2023'
7,1008,Francis,Njiru,NaN,M,False,78,False,NaN
8,1009,Joe,Ratemo,N/a,M,True,22,True,'22/1/2023'
9,1010,faith,Kathomi,N/a,Female,False,N/a,False,'23/1/2023'

In [35]:
df.tail()

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
8,1009,Joe,Ratemo,N/a,M,True,22,True,'22/1/2023'
9,1010,faith,Kathomi,N/a,Female,False,N/a,False,'23/1/2023'
10,1011,Lenny,Nyaga,N/a,M,True,31,True,'22/1/2023'
11,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
12,1004,Olive,Cira,N/a,F,False,30,False,'17/1/2023'

B. STEP 2: DATA PREPARATION

1.Checking and dropping duplicates

a)check duplicates

df.duplicated()- true means there is a duplicated record

In [36]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
dtype: bool

b)Check for sum of duplicates- if we had many record we would want to know he sum of duplicated records by

df.duplicated().sum()- Here we just have one duplicated record

In [37]:
df.duplicated().sum()

np.int64(1)

c)check for index of the duplicated record- we just add df.loc to the duplicated function

df.loc[df.duplicated()]
#df[df.duplicated()]-this also works just that .loc gives more flexibility when we want to select certain column names

Here we see the subset of the duplicated record and that it is index 11

In [38]:
df.loc[df.duplicated()]

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
11,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'

d)drop the duplicated record

df.drop_duplicates() _ You will notice that there that record index 11 is missing

In [39]:
df.drop_duplicates()

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
0,1001,Grace,Mwende,123-456-7098,Female,True,26,True,'14/1/2023'
1,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
2,1003,Emis,Leonard,NaN,F,True,60,True,'16/1/2023'
3,1004,Olive,Cira,N/a,F,False,40,False,'17/1/2023'
4,1005,leornard..,Thirika,304-762-2467,Male,True,89,True,'17/1/2023'
5,1006,/ignatius,Micheni,123-543-2345,M,False,62,False,'19/1/2023'
6,1007,_Kevin,Nyaga,876|678|3469,Male,True,32,True,'20/1/2023'
7,1008,Francis,Njiru,NaN,M,False,78,False,NaN
8,1009,Joe,Ratemo,N/a,M,True,22,True,'22/1/2023'
9,1010,faith,Kathomi,N/a,Female,False,N/a,False,'23/1/2023'
10,1011,Lenny,Nyaga,N/a,M,True,31,True,'22/1/2023'
12,1004,Olive,Cira,N/a,F,False,30,False,'17/1/2023'

However when we check the dataframe the index 11 has not been dropped- we can solve this two ways by using the inplace function or assigning df to the dropped function

In [40]:
df.drop_duplicates()
df

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
0,1001,Grace,Mwende,123-456-7098,Female,True,26,True,'14/1/2023'
1,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
2,1003,Emis,Leonard,NaN,F,True,60,True,'16/1/2023'
3,1004,Olive,Cira,N/a,F,False,40,False,'17/1/2023'
4,1005,leornard..,Thirika,304-762-2467,Male,True,89,True,'17/1/2023'
5,1006,/ignatius,Micheni,123-543-2345,M,False,62,False,'19/1/2023'
6,1007,_Kevin,Nyaga,876|678|3469,Male,True,32,True,'20/1/2023'
7,1008,Francis,Njiru,NaN,M,False,78,False,NaN
8,1009,Joe,Ratemo,N/a,M,True,22,True,'22/1/2023'
9,1010,faith,Kathomi,N/a,Female,False,N/a,False,'23/1/2023'
10,1011,Lenny,Nyaga,N/a,M,True,31,True,'22/1/2023'
11,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
12,1004,Olive,Cira,N/a,F,False,30,False,'17/1/2023'

using the inplace function
df.drop_duplicates(inplace=True)
df

In [41]:
df.drop_duplicates(inplace=True)
df

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
0,1001,Grace,Mwende,123-456-7098,Female,True,26,True,'14/1/2023'
1,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
2,1003,Emis,Leonard,NaN,F,True,60,True,'16/1/2023'
3,1004,Olive,Cira,N/a,F,False,40,False,'17/1/2023'
4,1005,leornard..,Thirika,304-762-2467,Male,True,89,True,'17/1/2023'
5,1006,/ignatius,Micheni,123-543-2345,M,False,62,False,'19/1/2023'
6,1007,_Kevin,Nyaga,876|678|3469,Male,True,32,True,'20/1/2023'
7,1008,Francis,Njiru,NaN,M,False,78,False,NaN
8,1009,Joe,Ratemo,N/a,M,True,22,True,'22/1/2023'
9,1010,faith,Kathomi,N/a,Female,False,N/a,False,'23/1/2023'
10,1011,Lenny,Nyaga,N/a,M,True,31,True,'22/1/2023'
12,1004,Olive,Cira,N/a,F,False,30,False,'17/1/2023'

assigning df to the dropped function
df=df.drop_duplicates()
df

In [42]:
df = df.drop_duplicates()
df

,Customer_id,Firstname,LastName,PhoneNumber,Gender,Other,age,Not_Useful_column,Sale date
0,1001,Grace,Mwende,123-456-7098,Female,True,26,True,'14/1/2023'
1,1002,John,Gitonga,321-654-0987,Male,False,30,False,'15/1/2023'
2,1003,Emis,Leonard,NaN,F,True,60,True,'16/1/2023'
3,1004,Olive,Cira,N/a,F,False,40,False,'17/1/2023'
4,1005,leornard..,Thirika,304-762-2467,Male,True,89,True,'17/1/2023'
5,1006,/ignatius,Micheni,123-543-2345,M,False,62,False,'19/1/2023'
6,1007,_Kevin,Nyaga,876|678|3469,Male,True,32,True,'20/1/2023'
7,1008,Francis,Njiru,NaN,M,False,78,False,NaN
8,1009,Joe,Ratemo,N/a,M,True,22,True,'22/1/2023'
9,1010,faith,Kathomi,N/a,Female,False,N/a,False,'23/1/2023'
10,1011,Lenny,Nyaga,N/a,M,True,31,True,'22/1/2023'
12,1004,Olive,Cira,N/a,F,False,30,False,'17/1/2023'

2. Drop irrelevant columns and rows-
a)Drop columns
Here we see that we don’t need the ‘Other’ and ‘Not_useful_column’ and need to drop them

df.drop([‘Other’,’Not_Useful_column’],axis=1,inplace=True)
df

In [43]:
df.drop(['Other','Not_Useful_column'], axis=1, inplace=True)
df

    Customer_id   Firstname LastName   PhoneNumber  Gender  age    Sale date
0          1001       Grace   Mwende  123-456-7098  Female   26  '14/1/2023'
1          1002        John  Gitonga  321-654-0987    Male   30  '15/1/2023'
2          1003        Emis  Leonard           NaN       F   60  '16/1/2023'
3          1004       Olive     Cira           N/a       F   40  '17/1/2023'
4          1005  leornard..  Thirika  304-762-2467    Male   89  '17/1/2023'
5          1006   /ignatius  Micheni  123-543-2345       M   62  '19/1/2023'
6          1007      _Kevin    Nyaga  876|678|3469    Male   32  '20/1/2023'
7          1008     Francis    Njiru           NaN       M   78          NaN
8          1009         Joe   Ratemo           N/a       M   22  '22/1/2023'
9          1010       faith  Kathomi           N/a  Female  N/a  '23/1/2023'
10         1011       Lenny    Nyaga           N/a       M   31  '22/1/2023'
12         1004       Olive     Cira           N/a       F   30  '17/1/2023'

You now see that the 2 columns are missing. Also noticed on the function we added inplace so as to save the results of the dataframe after removing the column and also we used axis=1 to remove columns while axis=0 removes rows

b)Drop Rows- drop record in index 12

df.drop(12,inplace=True)
df

In [44]:
df.drop(12,inplace=True)
df

    Customer_id   Firstname LastName   PhoneNumber  Gender  age    Sale date
0          1001       Grace   Mwende  123-456-7098  Female   26  '14/1/2023'
1          1002        John  Gitonga  321-654-0987    Male   30  '15/1/2023'
2          1003        Emis  Leonard           NaN       F   60  '16/1/2023'
3          1004       Olive     Cira           N/a       F   40  '17/1/2023'
4          1005  leornard..  Thirika  304-762-2467    Male   89  '17/1/2023'
5          1006   /ignatius  Micheni  123-543-2345       M   62  '19/1/2023'
6          1007      _Kevin    Nyaga  876|678|3469    Male   32  '20/1/2023'
7          1008     Francis    Njiru           NaN       M   78          NaN
8          1009         Joe   Ratemo           N/a       M   22  '22/1/2023'
9          1010       faith  Kathomi           N/a  Female  N/a  '23/1/2023'
10         1011       Lenny    Nyaga           N/a       M   31  '22/1/2023'

c)We can also decide to add a row- We need to define the row to add and then concatenate it to the datadrame

define the row- adding variable a

a= pd.DataFrame(
{
‘Customer_id’:1000,
‘Firstname’:’Harriet’,
‘LastName’:’Boore’,
‘PhoneNumber’:’1234567890',
‘Gender’:’F’,
‘age’:’60',
‘Sale date’:”’26/1/2023'”
},
index=[0]
)

In [ ]:
a = pd.DataFrame(
    {
        'Customer_id':1000,
        'Firstname':'Harriet',
        'LastName':'Boore',
        'PhoneNumber':'1234567890',
        'Gender':'F',
        'age':'60',
        'Sale date':"'26/1/2023"
    },
    index=[0]
)

add the row to the dataframe

df=pd.concat([a,df])
df

In [52]:
df = pd.concat([a,df])
df

    Customer_id   Firstname LastName   PhoneNumber  Gender  age    Sale date
0          1001       Grace   Mwende   123-456-789  Female   30   '14/1/2023
0          1000     Harriet    Boore    1234567890       F   60   '26/1/2023
1          1002        John  Gitonga  321-654-0987    Male   30  '15/1/2023'
2          1003        Emis  Leonard           NaN       F   60  '16/1/2023'
3          1004       Olive     Cira           N/a       F   40  '17/1/2023'
4          1005  leornard..  Thirika  304-762-2467    Male   89  '17/1/2023'
5          1006   /ignatius  Micheni  123-543-2345       M   62  '19/1/2023'
6          1007      _Kevin    Nyaga  876|678|3469    Male   32  '20/1/2023'
7          1008     Francis    Njiru           NaN       M   78          NaN
8          1009         Joe   Ratemo           N/a       M   22  '22/1/2023'
9          1010       faith  Kathomi           N/a  Female  N/a  '23/1/2023'
10         1011       Lenny    Nyaga           N/a       M   31  '22/1/2023'

Notice the added row at index 0. Also see that we have two indexes at index[0]therefore need to reset index . NB We need to reset indexes on row additions and deletions

df.reset_index(drop=True,inplace=True)
df

In [53]:
df.reset_index(drop=True, inplace=True)
df

    Customer_id   Firstname LastName   PhoneNumber  Gender  age    Sale date
0          1001       Grace   Mwende   123-456-789  Female   30   '14/1/2023
1          1000     Harriet    Boore    1234567890       F   60   '26/1/2023
2          1002        John  Gitonga  321-654-0987    Male   30  '15/1/2023'
3          1003        Emis  Leonard           NaN       F   60  '16/1/2023'
4          1004       Olive     Cira           N/a       F   40  '17/1/2023'
5          1005  leornard..  Thirika  304-762-2467    Male   89  '17/1/2023'
6          1006   /ignatius  Micheni  123-543-2345       M   62  '19/1/2023'
7          1007      _Kevin    Nyaga  876|678|3469    Male   32  '20/1/2023'
8          1008     Francis    Njiru           NaN       M   78          NaN
9          1009         Joe   Ratemo           N/a       M   22  '22/1/2023'
10         1010       faith  Kathomi           N/a  Female  N/a  '23/1/2023'
11         1011       Lenny    Nyaga           N/a       M   31  '22/1/2023'

drop=True removes the original index

3. Rename Columns- From our dataset we can see that the column names are not uniform we can rename

In [54]:
df.columns

Index(['Customer_id', 'Firstname', 'LastName', 'PhoneNumber', 'Gender', 'age',
       'Sale date'],
      dtype='object')

In [70]:
df=df.rename(columns={
    'Customer_id':'Customer_Id',
    'Firstname':'First_Name',
    'LastName':'Last_Name',
    'PhoneNumber':'Phone_number',
    'age':'Age',
    'Sale date':'Sale_Date'
})
df

    Customer_Id First_Name Last_Name  Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende   123-456-789      F   30 2023-01-14
1          1000    Harriet     Boore    1234567890      F   60 2023-01-26
2          1002       John   Gitonga  321-654-0987      F   30 2023-01-15
3          1003       Emis   Leonard           NaN      F   60 2023-01-16
4          1004      Olive      Cira           N/a      F   40 2023-01-17
5          1005   leornard   Thirika  304-762-2467      F   89 2023-01-17
6          1006   ignatius   Micheni  123-543-2345      M   62 2023-01-19
7          1007      Kevin     Nyaga  876|678|3469      F   32 2023-01-20
8          1008    Francis     Njiru           NaN      M   78        NaT
9          1009        Joe    Ratemo           N/a      M   22 2023-01-22
10         1010      faith   Kathomi           N/a      F  N/a 2023-01-23
11         1011      Lenny     Nyaga           N/a      M   31 2023-01-22

4. Converting data to the correct format- we need to convert Sale_Date to date since they are strings.

In [57]:
df.dtypes

Customer_Id     int64
First_Name     object
Last_Name      object
PhoneNumber    object
Gender         object
Age            object
Sale_Date      object
dtype: object

a)Access columns- we can access with two ways eg We try access ‘Sale_Date’ column

In [58]:
df.Sale_Date

0      '14/1/2023
1      '26/1/2023
2     '15/1/2023'
3     '16/1/2023'
4     '17/1/2023'
5     '17/1/2023'
6     '19/1/2023'
7     '20/1/2023'
8             NaN
9     '22/1/2023'
10    '23/1/2023'
11    '22/1/2023'
Name: Sale_Date, dtype: object

In [60]:
df['Sale_Date']

0      '14/1/2023
1      '26/1/2023
2     '15/1/2023'
3     '16/1/2023'
4     '17/1/2023'
5     '17/1/2023'
6     '19/1/2023'
7     '20/1/2023'
8             NaN
9     '22/1/2023'
10    '23/1/2023'
11    '22/1/2023'
Name: Sale_Date, dtype: object

b)Convert Sale_Date to Date

df[‘Sale_Date’]= pd.to_datetime(df[‘Sale_Date’],dayfirst=True)
df[‘Sale_Date’]


El parámetro dayfirst=True ya no es suficiente en versiones más recientes de pandas. Necesitas especificar el formato explícitamente o usar format='mixed'.
Soluciones:
Opción 1: Usar format='mixed' (más flexible)

In [63]:
df['Sale_Date']= pd.to_datetime(df['Sale_Date'],dayfirst=True, format='mixed')
df['Sale_Date']

0    2023-01-14
1    2023-01-26
2    2023-01-15
3    2023-01-16
4    2023-01-17
5    2023-01-17
6    2023-01-19
7    2023-01-20
8           NaT
9    2023-01-22
10   2023-01-23
11   2023-01-22
Name: Sale_Date, dtype: datetime64[ns]

5.Replacing values- We can see that the gender column is inconsistent.We have to convert Female to F and male to M for consistency

In [64]:
df

    Customer_Id  First_Name Last_Name   PhoneNumber  Gender  Age  Sale_Date
0          1001       Grace    Mwende   123-456-789  Female   30 2023-01-14
1          1000     Harriet     Boore    1234567890       F   60 2023-01-26
2          1002        John   Gitonga  321-654-0987    Male   30 2023-01-15
3          1003        Emis   Leonard           NaN       F   60 2023-01-16
4          1004       Olive      Cira           N/a       F   40 2023-01-17
5          1005  leornard..   Thirika  304-762-2467    Male   89 2023-01-17
6          1006   /ignatius   Micheni  123-543-2345       M   62 2023-01-19
7          1007      _Kevin     Nyaga  876|678|3469    Male   32 2023-01-20
8          1008     Francis     Njiru           NaN       M   78        NaT
9          1009         Joe    Ratemo           N/a       M   22 2023-01-22
10         1010       faith   Kathomi           N/a  Female  N/a 2023-01-23
11         1011       Lenny     Nyaga           N/a       M   31 2023-01-22

We use the str.replace function- both codes are correct
1.df.Gender.str.replace(‘Female’,’F’)
2.df[‘Gender’].str.replace(‘Female’,’F’)

In [66]:
df.Gender.str.replace('Female','F')
df['Gender'].str.replace('Female','F')

0        F
1        F
2     Male
3        F
4        F
5     Male
6        M
7     Male
8        M
9        M
10       F
11       M
Name: Gender, dtype: object

saving the values

df[‘Gender’]=df[‘Gender’].str.replace(‘Female’,’F’)
df[‘Gender’]=df[‘Gender’].str.replace(‘Male’,’M’)
df

In [68]:
df['Gender'] =df['Gender'].str.replace('Female','F')
df['Gender'] =df['Gender'].str.replace('Male','F')
df

    Customer_Id  First_Name Last_Name   PhoneNumber Gender  Age  Sale_Date
0          1001       Grace    Mwende   123-456-789      F   30 2023-01-14
1          1000     Harriet     Boore    1234567890      F   60 2023-01-26
2          1002        John   Gitonga  321-654-0987      F   30 2023-01-15
3          1003        Emis   Leonard           NaN      F   60 2023-01-16
4          1004       Olive      Cira           N/a      F   40 2023-01-17
5          1005  leornard..   Thirika  304-762-2467      F   89 2023-01-17
6          1006   /ignatius   Micheni  123-543-2345      M   62 2023-01-19
7          1007      _Kevin     Nyaga  876|678|3469      F   32 2023-01-20
8          1008     Francis     Njiru           NaN      M   78        NaT
9          1009         Joe    Ratemo           N/a      M   22 2023-01-22
10         1010       faith   Kathomi           N/a      F  N/a 2023-01-23
11         1011       Lenny     Nyaga           N/a      M   31 2023-01-22

6. Clean First_Name - first name has /,_ and .. characters on the name and need to remove them

df[‘First_Name’]=df[‘First_Name’].str.strip(‘123./_’)
df

In [69]:
df.First_Name = df.First_Name.str.strip('123./_')
df

    Customer_Id First_Name Last_Name   PhoneNumber Gender  Age  Sale_Date
0          1001      Grace    Mwende   123-456-789      F   30 2023-01-14
1          1000    Harriet     Boore    1234567890      F   60 2023-01-26
2          1002       John   Gitonga  321-654-0987      F   30 2023-01-15
3          1003       Emis   Leonard           NaN      F   60 2023-01-16
4          1004      Olive      Cira           N/a      F   40 2023-01-17
5          1005   leornard   Thirika  304-762-2467      F   89 2023-01-17
6          1006   ignatius   Micheni  123-543-2345      M   62 2023-01-19
7          1007      Kevin     Nyaga  876|678|3469      F   32 2023-01-20
8          1008    Francis     Njiru           NaN      M   78        NaT
9          1009        Joe    Ratemo           N/a      M   22 2023-01-22
10         1010      faith   Kathomi           N/a      F  N/a 2023-01-23
11         1011      Lenny     Nyaga           N/a      M   31 2023-01-22

First_Name is now clean

7. Remove alphanumeric on phone number-

df[‘Phone_Number’]=df[‘Phone_Number’].str.replace(‘[^a-zA-Z0–9]’,’’,regex=True)
df

In [71]:
df.Phone_number = df.Phone_number.str.replace('[^a-zA-Z0-9]','', regex=True)
df

    Customer_Id First_Name Last_Name Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende    123456789      F   30 2023-01-14
1          1000    Harriet     Boore   1234567890      F   60 2023-01-26
2          1002       John   Gitonga   3216540987      F   30 2023-01-15
3          1003       Emis   Leonard          NaN      F   60 2023-01-16
4          1004      Olive      Cira           Na      F   40 2023-01-17
5          1005   leornard   Thirika   3047622467      F   89 2023-01-17
6          1006   ignatius   Micheni   1235432345      M   62 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F   32 2023-01-20
8          1008    Francis     Njiru          NaN      M   78        NaT
9          1009        Joe    Ratemo           Na      M   22 2023-01-22
10         1010      faith   Kathomi           Na      F  N/a 2023-01-23
11         1011      Lenny     Nyaga           Na      M   31 2023-01-22

6. Checking and dropping NA(cleaning empty cells)

a)Check for null values

i)df.isna() — True means that the values are missing

In [72]:
df.isna()

    Customer_Id  First_Name  Last_Name  Phone_number  Gender    Age  Sale_Date
0         False       False      False         False   False  False      False
1         False       False      False         False   False  False      False
2         False       False      False         False   False  False      False
3         False       False      False          True   False  False      False
4         False       False      False         False   False  False      False
5         False       False      False         False   False  False      False
6         False       False      False         False   False  False      False
7         False       False      False         False   False  False      False
8         False       False      False          True   False  False       True
9         False       False      False         False   False  False      False
10        False       False      False         False   False  False      False
11        False       False      False         False   False  False      False

ii)Check the sum of the missing values

df.isna().sum()- shows the missing values in each column

In [73]:
df.isna().sum()

Customer_Id     0
First_Name      0
Last_Name       0
Phone_number    2
Gender          0
Age             0
Sale_Date       1
dtype: int64

b)We can handle missing values by dropping, replacing or filling

i)Filling- we can fill the missing values on the date column with a value

In [74]:
df

    Customer_Id First_Name Last_Name Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende    123456789      F   30 2023-01-14
1          1000    Harriet     Boore   1234567890      F   60 2023-01-26
2          1002       John   Gitonga   3216540987      F   30 2023-01-15
3          1003       Emis   Leonard          NaN      F   60 2023-01-16
4          1004      Olive      Cira           Na      F   40 2023-01-17
5          1005   leornard   Thirika   3047622467      F   89 2023-01-17
6          1006   ignatius   Micheni   1235432345      M   62 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F   32 2023-01-20
8          1008    Francis     Njiru          NaN      M   78        NaT
9          1009        Joe    Ratemo           Na      M   22 2023-01-22
10         1010      faith   Kathomi           Na      F  N/a 2023-01-23
11         1011      Lenny     Nyaga           Na      M   31 2023-01-22

In [75]:
df.Sale_Date = df.Sale_Date.fillna('2023/01/22')
df

    Customer_Id First_Name Last_Name Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende    123456789      F   30 2023-01-14
1          1000    Harriet     Boore   1234567890      F   60 2023-01-26
2          1002       John   Gitonga   3216540987      F   30 2023-01-15
3          1003       Emis   Leonard          NaN      F   60 2023-01-16
4          1004      Olive      Cira           Na      F   40 2023-01-17
5          1005   leornard   Thirika   3047622467      F   89 2023-01-17
6          1006   ignatius   Micheni   1235432345      M   62 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F   32 2023-01-20
8          1008    Francis     Njiru          NaN      M   78 2023-01-22
9          1009        Joe    Ratemo           Na      M   22 2023-01-22
10         1010      faith   Kathomi           Na      F  N/a 2023-01-23
11         1011      Lenny     Nyaga           Na      M   31 2023-01-22

ii)Replace of fill with a blank value- replace missing phone_numbers with blank
df[‘Phone_Number’]=df[‘Phone_Number’].fillna(‘’)
df

-Phone_number values are now blank

In [76]:
df.Phone_number =df.Phone_number.fillna('')
df

    Customer_Id First_Name Last_Name Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende    123456789      F   30 2023-01-14
1          1000    Harriet     Boore   1234567890      F   60 2023-01-26
2          1002       John   Gitonga   3216540987      F   30 2023-01-15
3          1003       Emis   Leonard                   F   60 2023-01-16
4          1004      Olive      Cira           Na      F   40 2023-01-17
5          1005   leornard   Thirika   3047622467      F   89 2023-01-17
6          1006   ignatius   Micheni   1235432345      M   62 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F   32 2023-01-20
8          1008    Francis     Njiru                   M   78 2023-01-22
9          1009        Joe    Ratemo           Na      M   22 2023-01-22
10         1010      faith   Kathomi           Na      F  N/a 2023-01-23
11         1011      Lenny     Nyaga           Na      M   31 2023-01-22

When we check sum of missing values we see that we have no missing values

In [77]:
df.isna().sum()

Customer_Id     0
First_Name      0
Last_Name       0
Phone_number    0
Gender          0
Age             0
Sale_Date       0
dtype: int64

But we still can see some values with N/a and blank, we need to handle that

In [78]:
df

    Customer_Id First_Name Last_Name Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende    123456789      F   30 2023-01-14
1          1000    Harriet     Boore   1234567890      F   60 2023-01-26
2          1002       John   Gitonga   3216540987      F   30 2023-01-15
3          1003       Emis   Leonard                   F   60 2023-01-16
4          1004      Olive      Cira           Na      F   40 2023-01-17
5          1005   leornard   Thirika   3047622467      F   89 2023-01-17
6          1006   ignatius   Micheni   1235432345      M   62 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F   32 2023-01-20
8          1008    Francis     Njiru                   M   78 2023-01-22
9          1009        Joe    Ratemo           Na      M   22 2023-01-22
10         1010      faith   Kathomi           Na      F  N/a 2023-01-23
11         1011      Lenny     Nyaga           Na      M   31 2023-01-22

iii)Replace Na with NaN since we can see that N/a is not read as a missing values by using the mask function

df=df.mask(df == ‘N/a’)
df

In [81]:
df= df.mask(df == 'N/a')
df

    Customer_Id First_Name Last_Name Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende    123456789      F   30 2023-01-14
1          1000    Harriet     Boore   1234567890      F   60 2023-01-26
2          1002       John   Gitonga   3216540987      F   30 2023-01-15
3          1003       Emis   Leonard                   F   60 2023-01-16
4          1004      Olive      Cira          NaN      F   40 2023-01-17
5          1005   leornard   Thirika   3047622467      F   89 2023-01-17
6          1006   ignatius   Micheni   1235432345      M   62 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F   32 2023-01-20
8          1008    Francis     Njiru                   M   78 2023-01-22
9          1009        Joe    Ratemo          NaN      M   22 2023-01-22
10         1010      faith   Kathomi          NaN      F  NaN 2023-01-23
11         1011      Lenny     Nyaga          NaN      M   31 2023-01-22

iv)fill blanks with NaN as well

df=df.mask(df == ‘’)
df

In [82]:
df = df.mask(df == '')
df

    Customer_Id First_Name Last_Name Phone_number Gender  Age  Sale_Date
0          1001      Grace    Mwende    123456789      F   30 2023-01-14
1          1000    Harriet     Boore   1234567890      F   60 2023-01-26
2          1002       John   Gitonga   3216540987      F   30 2023-01-15
3          1003       Emis   Leonard          NaN      F   60 2023-01-16
4          1004      Olive      Cira          NaN      F   40 2023-01-17
5          1005   leornard   Thirika   3047622467      F   89 2023-01-17
6          1006   ignatius   Micheni   1235432345      M   62 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F   32 2023-01-20
8          1008    Francis     Njiru          NaN      M   78 2023-01-22
9          1009        Joe    Ratemo          NaN      M   22 2023-01-22
10         1010      faith   Kathomi          NaN      F  NaN 2023-01-23
11         1011      Lenny     Nyaga          NaN      M   31 2023-01-22

v)Replace with mode,mean and median- the best solution is to replace with median value for that column. Median is a good choice because it is least likely to influence the distribution of the dataset overall. If the data is symmetric, then the mean and median will be the same value. If the dataset is not symmetric, then the mean is more likely to be skewed by outlier values, so the median is a better choice.

Mean
-Age is a string and when you run the mean function directly you will get a Type error therefore we need to convert Age from string to numeric same way we converted sale_date to date earlier

df[‘Age’]= pd.to_numeric(df[‘Age’])
df.dtypes

In [83]:
df.Age =pd.to_numeric(df.Age)
df.dtypes

Customer_Id              int64
First_Name              object
Last_Name               object
Phone_number            object
Gender                  object
Age                    float64
Sale_Date       datetime64[ns]
dtype: object

We can see that age has been converted to a float we can now replace the NaN with mean

In [84]:
df

    Customer_Id First_Name Last_Name Phone_number Gender   Age  Sale_Date
0          1001      Grace    Mwende    123456789      F  30.0 2023-01-14
1          1000    Harriet     Boore   1234567890      F  60.0 2023-01-26
2          1002       John   Gitonga   3216540987      F  30.0 2023-01-15
3          1003       Emis   Leonard          NaN      F  60.0 2023-01-16
4          1004      Olive      Cira          NaN      F  40.0 2023-01-17
5          1005   leornard   Thirika   3047622467      F  89.0 2023-01-17
6          1006   ignatius   Micheni   1235432345      M  62.0 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F  32.0 2023-01-20
8          1008    Francis     Njiru          NaN      M  78.0 2023-01-22
9          1009        Joe    Ratemo          NaN      M  22.0 2023-01-22
10         1010      faith   Kathomi          NaN      F   NaN 2023-01-23
11         1011      Lenny     Nyaga          NaN      M  31.0 2023-01-22

In [85]:
x = df.Age.mean()
df.Age = df.Age.fillna(x)
df

    Customer_Id First_Name Last_Name Phone_number Gender        Age  Sale_Date
0          1001      Grace    Mwende    123456789      F  30.000000 2023-01-14
1          1000    Harriet     Boore   1234567890      F  60.000000 2023-01-26
2          1002       John   Gitonga   3216540987      F  30.000000 2023-01-15
3          1003       Emis   Leonard          NaN      F  60.000000 2023-01-16
4          1004      Olive      Cira          NaN      F  40.000000 2023-01-17
5          1005   leornard   Thirika   3047622467      F  89.000000 2023-01-17
6          1006   ignatius   Micheni   1235432345      M  62.000000 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F  32.000000 2023-01-20
8          1008    Francis     Njiru          NaN      M  78.000000 2023-01-22
9          1009        Joe    Ratemo          NaN      M  22.000000 2023-01-22
10         1010      faith   Kathomi          NaN      F  48.545455 2023-01-23
11         1011      Lenny     Nyaga          NaN      M  31.000000 2023-01-22

You can see that now NaN on Age column has been filled with mean

Mode and Median
-The formula will be the same only that on the value of x you will replace with mode or median i.e

Mode

Median

In [86]:
x =df.Age.mode()
df.Age = df.Age.fillna(x)
df

    Customer_Id First_Name Last_Name Phone_number Gender        Age  Sale_Date
0          1001      Grace    Mwende    123456789      F  30.000000 2023-01-14
1          1000    Harriet     Boore   1234567890      F  60.000000 2023-01-26
2          1002       John   Gitonga   3216540987      F  30.000000 2023-01-15
3          1003       Emis   Leonard          NaN      F  60.000000 2023-01-16
4          1004      Olive      Cira          NaN      F  40.000000 2023-01-17
5          1005   leornard   Thirika   3047622467      F  89.000000 2023-01-17
6          1006   ignatius   Micheni   1235432345      M  62.000000 2023-01-19
7          1007      Kevin     Nyaga   8766783469      F  32.000000 2023-01-20
8          1008    Francis     Njiru          NaN      M  78.000000 2023-01-22
9          1009        Joe    Ratemo          NaN      M  22.000000 2023-01-22
10         1010      faith   Kathomi          NaN      F  48.545455 2023-01-23
11         1011      Lenny     Nyaga          NaN      M  31.000000 2023-01-22

we can see that the NaN are still there we can drop across where missing by

In [87]:
df.dropna()

   Customer_Id First_Name Last_Name Phone_number Gender   Age  Sale_Date
0         1001      Grace    Mwende    123456789      F  30.0 2023-01-14
1         1000    Harriet     Boore   1234567890      F  60.0 2023-01-26
2         1002       John   Gitonga   3216540987      F  30.0 2023-01-15
5         1005   leornard   Thirika   3047622467      F  89.0 2023-01-17
6         1006   ignatius   Micheni   1235432345      M  62.0 2023-01-19
7         1007      Kevin     Nyaga   8766783469      F  32.0 2023-01-20

we see that rows with NaN have been removed to save this you can assign this drop function to df or use inplace as true as seen earlier in the tutorial