What are we going to learn today?
Today we will learn to add new columns & rows with useful data and remove redundant columns & rows. We will also learn to combine two data sets and deal with their nuances.

Why is it important to learn?
In data science, we do two essential things to prepare a data set for analysis: first, we extract helpful information, and second, we clean redundant data from the data set. This can be achieved by cleaning the data by removing unnecessary columns and extracting valuable insights.

We will see an example of the Nutrition data set, where we want to analyze the percentage of Carbohydrates from total calories. This will be achieved by removing unnecessary columns and adding the percentage column.

How are we going to achieve today’s learning goal?
Plan for today is:

Adding columns with Index operator
Adding columns with Insert method
Removing columns
Adding rows with Append method
Adding rows and columns with Concat method
Removing rows

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../menu.csv')

Lets look at the first five rows.

In [4]:
df.head()

,Category,Item,Serving Size,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10

Let’s list all the columns of a data set using the info method.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 24 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Category                       260 non-null    object
 1   Item                           260 non-null    object
 2   Serving Size                   260 non-null    object
 3   Calories                       260 non-null    int64
 4   Calories from Fat              260 non-null    int64
 5   Total Fat                      260 non-null    float64
 6   Total Fat (% Daily Value)      260 non-null    int64
 7   Saturated Fat                  260 non-null    float64
 8   Saturated Fat (% Daily Value)  260 non-null    int64
 9   Trans Fat                      260 non-null    float64
 10  Cholesterol                    260 non-null    int64
 11  Cholesterol (% Daily Value)    260 non-null    int64
 12  Sodium                         260 non-null    int64
 13  Sodium (% Daily Value)         260 non-null    int64
 14  Carbohydrates                  260 non-null    int64
 15  Carbohydrates (% Daily Value)  260 non-null    int64
 16  Dietary Fiber                  260 non-null    int64
 17  Dietary Fiber (% Daily Value)  260 non-null    int64
 18  Sugars                         260 non-null    int64
 19  Protein                        260 non-null    int64
 20  Vitamin A (% Daily Value)      260 non-null    int64
 21  Vitamin C (% Daily Value)      260 non-null    int64
 22  Calcium (% Daily Value)        260 non-null    int64
 23  Iron (% Daily Value)           260 non-null    int64
dtypes: float64(3), int64(18), object(3)
memory usage: 48.9+ KB

Adding columns with Indexing Operator
This section will add a Carbohydrates Percentage column to the data set. We will achieve this result by applying the percentage formula to each value in the Carbohydrates and Calories column. The result will be saved in the new column.

Formula

Carbohydrates Percentage = (Carbohydrates/Calories) x 100

It is the first method to create/add a new column, write a new column name in indexing operator [ ] and assign a new value/condition.

In [6]:
df['Carbohydrates Percentage '] = df['Carbohydrates'] / df['Calories'] * 100

Let us display the columns relevant to our goal and see the new column Carbohydrates Percentage with the percentage of carbohydrates in each item.

In [9]:
# Fíjate en el espacio extra al final de Percentage
df.loc[ : , ['Category', 'Item', 'Calories', 'Carbohydrates', 'Carbohydrates Percentage ']].head()

,Category,Item,Calories,Carbohydrates,Carbohydrates Percentage
0,Breakfast,Egg McMuffin,300,31,10.333333
1,Breakfast,Egg White Delight,250,30,12.000000
2,Breakfast,Sausage McMuffin,370,29,7.837838
3,Breakfast,Sausage McMuffin with Egg,450,30,6.666667
4,Breakfast,Sausage McMuffin with Egg Whites,400,30,7.500000

A useful insight for those who need to manage their carbohydrates intake.. :)

Adding columns with Insert method
This section will add a Protein Percentage column to the data set using the insert method. We will achieve this result by applying the percentage formula to each value in Protein and Calories column. The result will be saved in the new column.

Formula

Protein Percentage = (Protein/Calories) x 100

Insert method is used to insert or create a column at a specified location. It takes four parameters, location where you want to insert a new column, new column name, value and allow_duplicates whether you want to allow duplicates column name or not.

In [11]:
df.insert(4, 'Protein Percentage', df['Protein'] / df['Calories'] * 100, False)

Lets view a few columns.

In [12]:
df.head()

,Category,Item,Serving Size,Calories,Protein Percentage,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),...,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value),Carbohydrates Percentage
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,5.666667,120,13.0,20,5.0,25,...,10,4,17,3,17,10,0,25,15,10.333333
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,7.200000,70,8.0,12,3.0,15,...,10,4,17,3,18,6,0,25,8,12.000000
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,3.783784,200,23.0,35,8.0,42,...,10,4,17,2,14,8,0,25,10,7.837838
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,4.666667,250,28.0,43,10.0,52,...,10,4,17,2,21,15,0,30,15,6.666667
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,5.250000,210,23.0,35,8.0,42,...,10,4,17,2,21,6,0,25,10,7.500000

Now we can see that column at index number four is Protein Percentage.

Removing/Dropping Columns
Let us remove/drop the column Protein in percentage, and if we want to drop more than one column, we will pass a list of those columns.

For dropping columns in Pandas data frame, we will use the drop() method.
The drop() method is used to drop/remove specified columns. In order to change in the original data frame, we will use the inplace=True parameter.

In [14]:

df.drop(columns='Protein Percentage', inplace=True)
df.head()

,Category,Item,Serving Size,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value),Carbohydrates Percentage
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,10,4,17,3,17,10,0,25,15,10.333333
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,10,4,17,3,18,6,0,25,8,12.000000
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,10,4,17,2,14,8,0,25,10,7.837838
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,10,4,17,2,21,15,0,30,15,6.666667
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,10,4,17,2,21,6,0,25,10,7.500000

Let’s display the five rows of the data frame, and you will see there is no column Protein percentage at index number 4.

Adding rows with Concat method
So far, we have seen adding and removing columns, and now we will see adding and removing rows. For this purpose, we will create two small data sets data1 and data2.

Create a dictionary and convert if into a Pandas data frame.

In [ ]:
student1 = {
"Id": ['cs-01', 'mth-02', 'eng-03', 'phy-04', 'mth-05', 'cs-06'],
"Name": ["Fatima", 'Noureen', 'Salman', 'Sana', 'Jack', 'Ali'],
"subject": ['computer science', 'math', 'english', 'physics', 'statistics', 'programming'],
"marks": [45, 90, 60, 37, 49, 50]
}
data1 = pd.DataFrame(student1)
data1

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50

Output gives us a data frame with 6 rows and 4 columns.

In [16]:
student2 = {
"Id": ['cs-08', 'mth-0'],
"Name": ["Adam", 'Steve'],
"subject": ['compu' 'science', 'math'],
"marks": [45, 90]
}
data2 = pd.DataFrame(student2)
data2

      Id   Name       subject  marks
0  cs-08   Adam  compuscience     45
1  mth-0  Steve          math     90

Data frame with 2 rows and 4 columns

Adding rows with Append method
Now lets append data1 and data2 data frames with the append() method.

Append:Pandas append() method appends the rows to the bottom of the first data set.

We will also use ignore_index parameter and set it to True; this resets the index of the appended data set. Otherwise if it is set to False the data frame retains original indexing. Lets see both out puts.

In [24]:
df_resultado = pd.concat([data1, data2], ignore_index=False)
df_resultado

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50
0   cs-08     Adam      compuscience     45
1   mth-0    Steve              math     90

In [25]:
df_resultado = pd.concat([data1, data2], ignore_index=True)
df_resultado

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50
6   cs-08     Adam      compuscience     45
7   mth-0    Steve              math     90

Adding rows with Concat method
Another method to add rows in pandas is with the concat function.

The concat() method works with columns and rows. It takes an axis parameter which differtnaites the operation. On axis set to rows, the concat method works the same as the append method, but on columns, it is concat by columns, not rows.

Let’s see a practical example

Axis set to 1 the concat operation is for columns

In [26]:
pd.concat([data1, data2], axis=1)

       Id     Name           subject  marks     Id   Name       subject  marks
0   cs-01   Fatima  computer science     45  cs-08   Adam  compuscience   45.0
1  mth-02  Noureen              math     90  mth-0  Steve          math   90.0
2  eng-03   Salman           english     60    NaN    NaN           NaN    NaN
3  phy-04     Sana           physics     37    NaN    NaN           NaN    NaN
4  mth-05     Jack        statistics     49    NaN    NaN           NaN    NaN
5   cs-06      Ali       programming     50    NaN    NaN           NaN    NaN

NaN values are filler values for places in the data set where there is no data available.

Axis set to 0 the concat operation is for rows

In [28]:
data1 = pd.concat([data1, data2], axis=0, ignore_index=True)
data1

       Id     Name           subject  marks
0   cs-01   Fatima  computer science     45
1  mth-02  Noureen              math     90
2  eng-03   Salman           english     60
3  phy-04     Sana           physics     37
4  mth-05     Jack        statistics     49
5   cs-06      Ali       programming     50
6   cs-08     Adam      compuscience     45
7   mth-0    Steve              math     90

We can see the difference in the output when an axis is set to 1 (columns). It concat data2 in data1 by columns and insert NaN values in other rows because we have only two rows in data2.

But on axis 0 (rows) works the same as the append method.

Removing rows
To remove/drop rows, same the drop method is used. Instead of columns parameter, we will use index.

In [29]:
data1.drop(index = [0,7])

       Id     Name       subject  marks
1  mth-02  Noureen          math     90
2  eng-03   Salman       english     60
3  phy-04     Sana       physics     37
4  mth-05     Jack    statistics     49
5   cs-06      Ali   programming     50
6   cs-08     Adam  compuscience     45

Row numbers 0 and 7 are deleted. Once again, if we want to change the original data frame, don’t forget to set inplace the parameter equal to True.