In [1]:
import pandas as pd
import numpy as np

In [2]:
df_empleados = pd.DataFrame({
 'nombre': ['Ana', 'Juan', 'María', 'Pedro', 'Laura'],
 'edad': [28, 35, 42, 31, 38],
 'salario_mensual': [3000, 4500, 6000, 3800, 5200],
 'años_experiencia': [3, 8, 15, 5, 10],
 'departamento': ['IT', 'Ventas', 'IT', 'Marketing', 'Ventas']
})

1. Calcular el salario anual

In [3]:
df_empleados['salario_anual'] = df_empleados['salario_mensual'] * 12
print(df_empleados)

  nombre  edad  salario_mensual  años_experiencia departamento  salario_anual
0    Ana    28             3000                 3           IT          36000
1   Juan    35             4500                 8       Ventas          54000
2  María    42             6000                15           IT          72000
3  Pedro    31             3800                 5    Marketing          45600
4  Laura    38             5200                10       Ventas          62400

2. Calcular el salario por año de experiencia

In [4]:
df_empleados['salario_exp'] = df_empleados['salario_mensual'] / df_empleados['años_experiencia']
print(df_empleados)

  nombre  edad  salario_mensual  años_experiencia departamento  salario_anual  \
0    Ana    28             3000                 3           IT          36000
1   Juan    35             4500                 8       Ventas          54000
2  María    42             6000                15           IT          72000
3  Pedro    31             3800                 5    Marketing          45600
4  Laura    38             5200                10       Ventas          62400

   salario_exp
0       1000.0
1        562.5
2        400.0
3        760.0
4        520.0

3. Crear grupos de edad: 'Junior' (< 30), 'Mid' (30-40), 'Senior' (> 40)

In [5]:
bins = [0, 29, 41, 100]
labels = ['Junior', 'Mid', 'Senior']

df_empleados['grupo_edad'] = pd.cut(df_empleados['edad'], bins=bins, labels=labels)
print(df_empleados)

  nombre  edad  salario_mensual  años_experiencia departamento  salario_anual  \
0    Ana    28             3000                 3           IT          36000
1   Juan    35             4500                 8       Ventas          54000
2  María    42             6000                15           IT          72000
3  Pedro    31             3800                 5    Marketing          45600
4  Laura    38             5200                10       Ventas          62400

   salario_exp grupo_edad
0       1000.0     Junior
1        562.5        Mid
2        400.0     Senior
3        760.0        Mid
4        520.0        Mid

4. Crear una variable dummy para el departamento IT

In [6]:
df_empleados['es_IT'] = np.where(df_empleados['departamento'] == 'IT', 1, 0)
print(df_empleados)

  nombre  edad  salario_mensual  años_experiencia departamento  salario_anual  \
0    Ana    28             3000                 3           IT          36000
1   Juan    35             4500                 8       Ventas          54000
2  María    42             6000                15           IT          72000
3  Pedro    31             3800                 5    Marketing          45600
4  Laura    38             5200                10       Ventas          62400

   salario_exp grupo_edad  es_IT
0       1000.0     Junior      1
1        562.5        Mid      0
2        400.0     Senior      1
3        760.0        Mid      0
4        520.0        Mid      0

5. Calcular la mediana de salario por departamento y crear una columna con esta
información

In [7]:
df_empleados['mediana_salario'] = df_empleados.groupby(df_empleados['departamento'])['salario_mensual'].transform('median')
print(df_empleados)

  nombre  edad  salario_mensual  años_experiencia departamento  salario_anual  \
0    Ana    28             3000                 3           IT          36000
1   Juan    35             4500                 8       Ventas          54000
2  María    42             6000                15           IT          72000
3  Pedro    31             3800                 5    Marketing          45600
4  Laura    38             5200                10       Ventas          62400

   salario_exp grupo_edad  es_IT  mediana_salario
0       1000.0     Junior      1           4500.0
1        562.5        Mid      0           4850.0
2        400.0     Senior      1           4500.0
3        760.0        Mid      0           3800.0
4        520.0        Mid      0           4850.0

Ejercicio 2: Análisis Temporal de Ventas
Crea un dataset de ventas diarias y realiza las siguientes transformaciones:

In [8]:
# Semilla para que nos salgan los mismos números aleatorios
np.random.seed(42)

df_ventas = pd.DataFrame({
    'fecha': pd.date_range('2024-01-01', periods=90, freq='D'),
    'ventas_diarias': np.random.randint(1000, 5000, 90)
})

print(df_ventas.head())

       fecha  ventas_diarias
0 2024-01-01            4174
1 2024-01-02            4507
2 2024-01-03            1860
3 2024-01-04            2294
4 2024-01-05            2130

1. Extraer mes, día de la semana, y número de semana del año

In [9]:
df_ventas['mes'] = df_ventas['fecha'].dt.month
df_ventas['dia'] = df_ventas['fecha'].dt.day_name()
df_ventas['semana'] = df_ventas['fecha'].dt.isocalendar().week
print(df_ventas)

        fecha  ventas_diarias  mes        dia  semana
0  2024-01-01            4174    1     Monday       1
1  2024-01-02            4507    1    Tuesday       1
2  2024-01-03            1860    1  Wednesday       1
3  2024-01-04            2294    1   Thursday       1
4  2024-01-05            2130    1     Friday       1
..        ...             ...  ...        ...     ...
85 2024-03-26            3253    3    Tuesday      13
86 2024-03-27            4152    3  Wednesday      13
87 2024-03-28            2955    3   Thursday      13
88 2024-03-29            2585    3     Friday      13
89 2024-03-30            4943    3   Saturday      13

[90 rows x 5 columns]

2. Crear una variable binaria que indique si es fin de semana

In [10]:
df_ventas['dummy_findesemana'] = np.where((df_ventas['dia'] == 'Saturday') | (df_ventas['dia'] == 'Sunday'), 1, 0)
print(df_ventas)

        fecha  ventas_diarias  mes        dia  semana  dummy_findesemana
0  2024-01-01            4174    1     Monday       1                  0
1  2024-01-02            4507    1    Tuesday       1                  0
2  2024-01-03            1860    1  Wednesday       1                  0
3  2024-01-04            2294    1   Thursday       1                  0
4  2024-01-05            2130    1     Friday       1                  0
..        ...             ...  ...        ...     ...                ...
85 2024-03-26            3253    3    Tuesday      13                  0
86 2024-03-27            4152    3  Wednesday      13                  0
87 2024-03-28            2955    3   Thursday      13                  0
88 2024-03-29            2585    3     Friday      13                  0
89 2024-03-30            4943    3   Saturday      13                  1

[90 rows x 6 columns]

3. Calcular la media móvil de 7 días

In [11]:
df_ventas['media_movil_7d'] = df_ventas['ventas_diarias'].rolling(window=7).mean()
print(df_ventas)

        fecha  ventas_diarias  mes        dia  semana  dummy_findesemana  \
0  2024-01-01            4174    1     Monday       1                  0
1  2024-01-02            4507    1    Tuesday       1                  0
2  2024-01-03            1860    1  Wednesday       1                  0
3  2024-01-04            2294    1   Thursday       1                  0
4  2024-01-05            2130    1     Friday       1                  0
..        ...             ...  ...        ...     ...                ...
85 2024-03-26            3253    3    Tuesday      13                  0
86 2024-03-27            4152    3  Wednesday      13                  0
87 2024-03-28            2955    3   Thursday      13                  0
88 2024-03-29            2585    3     Friday      13                  0
89 2024-03-30            4943    3   Saturday      13                  1

    media_movil_7d
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
..             ...
85     2942.571429
86     2963.857143
87     3032.000000
88     2758.571429
89     2956.714286

[90 rows x 7 columns]

4. Crear features de lag de 1, 3 y 7 días

In [12]:
df_ventas['lag_1'] = df_ventas['ventas_diarias'].shift(1)
df_ventas['lag_3'] = df_ventas['ventas_diarias'].shift(3)
df_ventas['lag_7'] = df_ventas['ventas_diarias'].shift(7)
print(df_ventas)

        fecha  ventas_diarias  mes        dia  semana  dummy_findesemana  \
0  2024-01-01            4174    1     Monday       1                  0
1  2024-01-02            4507    1    Tuesday       1                  0
2  2024-01-03            1860    1  Wednesday       1                  0
3  2024-01-04            2294    1   Thursday       1                  0
4  2024-01-05            2130    1     Friday       1                  0
..        ...             ...  ...        ...     ...                ...
85 2024-03-26            3253    3    Tuesday      13                  0
86 2024-03-27            4152    3  Wednesday      13                  0
87 2024-03-28            2955    3   Thursday      13                  0
88 2024-03-29            2585    3     Friday      13                  0
89 2024-03-30            4943    3   Saturday      13                  1

    media_movil_7d   lag_1   lag_3   lag_7
0              NaN     NaN     NaN     NaN
1              NaN  4174.0     NaN     NaN
2              NaN  4507.0     NaN     NaN
3              NaN  1860.0  4174.0     NaN
4              NaN  2294.0  4507.0     NaN
..             ...     ...     ...     ...
85     2942.571429  1034.0  3556.0  2390.0
86     2963.857143  3253.0  1775.0  4003.0
87     3032.000000  4152.0  1034.0  2478.0
88     2758.571429  2955.0  3253.0  4499.0
89     2956.714286  2585.0  4152.0  3556.0

[90 rows x 10 columns]

5. Calcular el crecimiento porcentual día a día

In [13]:
df_ventas['crecimiento_pct'] = df_ventas['ventas_diarias'].pct_change()
print(df_ventas)

        fecha  ventas_diarias  mes        dia  semana  dummy_findesemana  \
0  2024-01-01            4174    1     Monday       1                  0
1  2024-01-02            4507    1    Tuesday       1                  0
2  2024-01-03            1860    1  Wednesday       1                  0
3  2024-01-04            2294    1   Thursday       1                  0
4  2024-01-05            2130    1     Friday       1                  0
..        ...             ...  ...        ...     ...                ...
85 2024-03-26            3253    3    Tuesday      13                  0
86 2024-03-27            4152    3  Wednesday      13                  0
87 2024-03-28            2955    3   Thursday      13                  0
88 2024-03-29            2585    3     Friday      13                  0
89 2024-03-30            4943    3   Saturday      13                  1

    media_movil_7d   lag_1   lag_3   lag_7  crecimiento_pct
0              NaN     NaN     NaN     NaN              NaN
1              NaN  4174.0     NaN     NaN         0.079780
2              NaN  4507.0     NaN     NaN        -0.587309
3              NaN  1860.0  4174.0     NaN         0.233333
4              NaN  2294.0  4507.0     NaN        -0.071491
..             ...     ...     ...     ...              ...
85     2942.571429  1034.0  3556.0  2390.0         2.146035
86     2963.857143  3253.0  1775.0  4003.0         0.276360
87     3032.000000  4152.0  1034.0  2478.0        -0.288295
88     2758.571429  2955.0  3253.0  4499.0        -0.125212
89     2956.714286  2585.0  4152.0  3556.0         0.912186

[90 rows x 11 columns]

6. Identificar si las ventas están por encima o debajo del promedio histórico

In [14]:
df_ventas['media_ventas'] = df_ventas['ventas_diarias'].mean()
df_ventas['rendimiento'] = np.where(df_ventas['ventas_diarias'] > df_ventas['media_ventas'], 'Superior', 'Inferior')
print(df_ventas)

        fecha  ventas_diarias  mes        dia  semana  dummy_findesemana  \
0  2024-01-01            4174    1     Monday       1                  0
1  2024-01-02            4507    1    Tuesday       1                  0
2  2024-01-03            1860    1  Wednesday       1                  0
3  2024-01-04            2294    1   Thursday       1                  0
4  2024-01-05            2130    1     Friday       1                  0
..        ...             ...  ...        ...     ...                ...
85 2024-03-26            3253    3    Tuesday      13                  0
86 2024-03-27            4152    3  Wednesday      13                  0
87 2024-03-28            2955    3   Thursday      13                  0
88 2024-03-29            2585    3     Friday      13                  0
89 2024-03-30            4943    3   Saturday      13                  1

    media_movil_7d   lag_1   lag_3   lag_7  crecimiento_pct  media_ventas  \
0              NaN     NaN     NaN     NaN              NaN   3094.866667
1              NaN  4174.0     NaN     NaN         0.079780   3094.866667
2              NaN  4507.0     NaN     NaN        -0.587309   3094.866667
3              NaN  1860.0  4174.0     NaN         0.233333   3094.866667
4              NaN  2294.0  4507.0     NaN        -0.071491   3094.866667
..             ...     ...     ...     ...              ...           ...
85     2942.571429  1034.0  3556.0  2390.0         2.146035   3094.866667
86     2963.857143  3253.0  1775.0  4003.0         0.276360   3094.866667
87     3032.000000  4152.0  1034.0  2478.0        -0.288295   3094.866667
88     2758.571429  2955.0  3253.0  4499.0        -0.125212   3094.866667
89     2956.714286  2585.0  4152.0  3556.0         0.912186   3094.866667

   rendimiento
0     Superior
1     Superior
2     Inferior
3     Inferior
4     Inferior
..         ...
85    Superior
86    Superior
87    Inferior
88    Inferior
89    Superior

[90 rows x 13 columns]

Ejercicio 3: Análisis de Clientes E-commerce

In [15]:
df_transacciones = pd.DataFrame({
    'cliente_id': [1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4],
    'fecha': pd.to_datetime(['2024-01-05', '2024-02-10', '2024-01-15',
                             '2024-02-20', '2024-03-25', '2024-01-08',
                             '2024-03-15', '2024-01-20', '2024-02-05',
                             '2024-02-25', '2024-03-30']),
    'monto': [100, 150, 80, 120, 90, 200, 180, 50, 60, 55, 70],
    'categoria': ['Electrónica', 'Ropa', 'Hogar', 'Electrónica', 'Ropa',
                  'Electrónica', 'Electrónica', 'Hogar', 'Hogar', 'Hogar', 'Hogar']
})

print(df_transacciones)

    cliente_id      fecha  monto    categoria
0            1 2024-01-05    100  Electrónica
1            1 2024-02-10    150         Ropa
2            2 2024-01-15     80        Hogar
3            2 2024-02-20    120  Electrónica
4            2 2024-03-25     90         Ropa
5            3 2024-01-08    200  Electrónica
6            3 2024-03-15    180  Electrónica
7            4 2024-01-20     50        Hogar
8            4 2024-02-05     60        Hogar
9            4 2024-02-25     55        Hogar
10           4 2024-03-30     70        Hogar

1. Calcular el número total de transacciones por cliente

In [16]:
df_transacciones['transacciones_totales'] = df_transacciones.groupby('cliente_id')['fecha'].transform('count')
print(df_transacciones)

    cliente_id      fecha  monto    categoria  transacciones_totales
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

2. Calcular el monto total gastado por cliente

In [17]:
df_transacciones['monto_total'] = df_transacciones.groupby('cliente_id')['monto'].transform('sum')
print(df_transacciones)

    cliente_id      fecha  monto    categoria  transacciones_totales  \
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

    monto_total
0           250
1           250
2           290
3           290
4           290
5           380
6           380
7           235
8           235
9           235
10          235

3. Calcular el ticket promedio por cliente

In [18]:
df_transacciones['ticket_cliente'] = df_transacciones.groupby('cliente_id')['monto'].transform('mean')
print(df_transacciones)

    cliente_id      fecha  monto    categoria  transacciones_totales  \
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

    monto_total  ticket_cliente
0           250      125.000000
1           250      125.000000
2           290       96.666667
3           290       96.666667
4           290       96.666667
5           380      190.000000
6           380      190.000000
7           235       58.750000
8           235       58.750000
9           235       58.750000
10          235       58.750000

4. Calcular los días desde la primera compra para cada transacción

In [19]:
df_transacciones['fecha_primera_compra'] = df_transacciones.groupby('cliente_id')['fecha'].transform('min')
df_transacciones['dias_desde_inicio'] = (df_transacciones['fecha'] - df_transacciones['fecha_primera_compra']).dt.days
print(df_transacciones)

    cliente_id      fecha  monto    categoria  transacciones_totales  \
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

    monto_total  ticket_cliente fecha_primera_compra  dias_desde_inicio
0           250      125.000000           2024-01-05                  0
1           250      125.000000           2024-01-05                 36
2           290       96.666667           2024-01-15                  0
3           290       96.666667           2024-01-15                 36
4           290       96.666667           2024-01-15                 70
5           380      190.000000           2024-01-08                  0
6           380      190.000000           2024-01-08                 67
7           235       58.750000           2024-01-20                  0
8           235       58.750000           2024-01-20                 16
9           235       58.750000           2024-01-20                 36
10          235       58.750000           2024-01-20                 70

5. Calcular el tiempo promedio entre compras por cliente

In [20]:
df_transacciones['diferencia_entre_fechas'] = df_transacciones.groupby('cliente_id')['fecha'].diff()
df_transacciones['promedio_entre_fechas'] = df_transacciones.groupby('cliente_id')['diferencia_entre_fechas'].transform('mean')
df_transacciones['diferencia_entre_fechas'] = df_transacciones['diferencia_entre_fechas'].dt.days
df_transacciones['promedio_entre_fechas'] = df_transacciones['promedio_entre_fechas'].dt.days
print(df_transacciones)

    cliente_id      fecha  monto    categoria  transacciones_totales  \
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

    monto_total  ticket_cliente fecha_primera_compra  dias_desde_inicio  \
0           250      125.000000           2024-01-05                  0
1           250      125.000000           2024-01-05                 36
2           290       96.666667           2024-01-15                  0
3           290       96.666667           2024-01-15                 36
4           290       96.666667           2024-01-15                 70
5           380      190.000000           2024-01-08                  0
6           380      190.000000           2024-01-08                 67
7           235       58.750000           2024-01-20                  0
8           235       58.750000           2024-01-20                 16
9           235       58.750000           2024-01-20                 36
10          235       58.750000           2024-01-20                 70

    diferencia_entre_fechas  promedio_entre_fechas
0                       NaN                     36
1                      36.0                     36
2                       NaN                     35
3                      36.0                     35
4                      34.0                     35
5                       NaN                     67
6                      67.0                     67
7                       NaN                     23
8                      16.0                     23
9                      20.0                     23
10                     34.0                     23

6. Identificar la categoría más comprada por cada cliente

In [21]:
# Por cada cliente (groupby), x = categoria por cliente, busca la categoría más repetida (.mode()), 
# y si hay un empate, dame la primera que encuentres (.iloc[0])."

df_transacciones['categ_mas_comprada_cliente'] = df_transacciones.groupby('cliente_id')['categoria'].transform(lambda x: x.mode().iloc[0])
print(df_transacciones)

    cliente_id      fecha  monto    categoria  transacciones_totales  \
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

    monto_total  ticket_cliente fecha_primera_compra  dias_desde_inicio  \
0           250      125.000000           2024-01-05                  0
1           250      125.000000           2024-01-05                 36
2           290       96.666667           2024-01-15                  0
3           290       96.666667           2024-01-15                 36
4           290       96.666667           2024-01-15                 70
5           380      190.000000           2024-01-08                  0
6           380      190.000000           2024-01-08                 67
7           235       58.750000           2024-01-20                  0
8           235       58.750000           2024-01-20                 16
9           235       58.750000           2024-01-20                 36
10          235       58.750000           2024-01-20                 70

    diferencia_entre_fechas  promedio_entre_fechas categ_mas_comprada_cliente
0                       NaN                     36                Electrónica
1                      36.0                     36                Electrónica
2                       NaN                     35                Electrónica
3                      36.0                     35                Electrónica
4                      34.0                     35                Electrónica
5                       NaN                     67                Electrónica
6                      67.0                     67                Electrónica
7                       NaN                     23                      Hogar
8                      16.0                     23                      Hogar
9                      20.0                     23                      Hogar
10                     34.0                     23                      Hogar

7. Crear una variable RFM simplificada:

    R (Recency): días desde la última compra

    F (Frequency): número de compras

    M (Monetary): gasto total

    Aquí solo cacularé la recencia en la siguiente celda haré un rank para concatenar el RFM

In [22]:
fecha_actual = df_transacciones['fecha'].max()
fecha_ultima_compra = df_transacciones.groupby('cliente_id')['fecha'].transform('max')
df_transacciones['recencia_dias'] = (fecha_actual - fecha_ultima_compra).dt.days
print(df_transacciones)

    cliente_id      fecha  monto    categoria  transacciones_totales  \
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

    monto_total  ticket_cliente fecha_primera_compra  dias_desde_inicio  \
0           250      125.000000           2024-01-05                  0
1           250      125.000000           2024-01-05                 36
2           290       96.666667           2024-01-15                  0
3           290       96.666667           2024-01-15                 36
4           290       96.666667           2024-01-15                 70
5           380      190.000000           2024-01-08                  0
6           380      190.000000           2024-01-08                 67
7           235       58.750000           2024-01-20                  0
8           235       58.750000           2024-01-20                 16
9           235       58.750000           2024-01-20                 36
10          235       58.750000           2024-01-20                 70

    diferencia_entre_fechas  promedio_entre_fechas categ_mas_comprada_cliente  \
0                       NaN                     36                Electrónica
1                      36.0                     36                Electrónica
2                       NaN                     35                Electrónica
3                      36.0                     35                Electrónica
4                      34.0                     35                Electrónica
5                       NaN                     67                Electrónica
6                      67.0                     67                Electrónica
7                       NaN                     23                      Hogar
8                      16.0                     23                      Hogar
9                      20.0                     23                      Hogar
10                     34.0                     23                      Hogar

    recencia_dias
0              49
1              49
2               5
3               5
4               5
5              15
6              15
7               0
8               0
9               0
10              0

In [24]:
df_transacciones['F_rank'] = df_transacciones['transacciones_totales'].rank(method='first', ascending=True)
df_transacciones['M_rank'] = df_transacciones['monto_total'].rank(method='first', ascending=True)
df_transacciones['R_rank'] = df_transacciones['recencia_dias'].rank(method='first', ascending=False)

df_transacciones['RFM_Score'] = (
    df_transacciones['R_rank'].astype(int).astype(str) + 
    df_transacciones['F_rank'].astype(int).astype(str) + 
    df_transacciones['M_rank'].astype(int).astype(str)
)
print(df_transacciones)
display(df_transacciones[['cliente_id', 'R_rank', 'F_rank', 'M_rank', 'RFM_Score']])

    cliente_id      fecha  monto    categoria  transacciones_totales  \
0            1 2024-01-05    100  Electrónica                      2
1            1 2024-02-10    150         Ropa                      2
2            2 2024-01-15     80        Hogar                      3
3            2 2024-02-20    120  Electrónica                      3
4            2 2024-03-25     90         Ropa                      3
5            3 2024-01-08    200  Electrónica                      2
6            3 2024-03-15    180  Electrónica                      2
7            4 2024-01-20     50        Hogar                      4
8            4 2024-02-05     60        Hogar                      4
9            4 2024-02-25     55        Hogar                      4
10           4 2024-03-30     70        Hogar                      4

    monto_total  ticket_cliente fecha_primera_compra  dias_desde_inicio  \
0           250      125.000000           2024-01-05                  0
1           250      125.000000           2024-01-05                 36
2           290       96.666667           2024-01-15                  0
3           290       96.666667           2024-01-15                 36
4           290       96.666667           2024-01-15                 70
5           380      190.000000           2024-01-08                  0
6           380      190.000000           2024-01-08                 67
7           235       58.750000           2024-01-20                  0
8           235       58.750000           2024-01-20                 16
9           235       58.750000           2024-01-20                 36
10          235       58.750000           2024-01-20                 70

    diferencia_entre_fechas  promedio_entre_fechas categ_mas_comprada_cliente  \
0                       NaN                     36                Electrónica
1                      36.0                     36                Electrónica
2                       NaN                     35                Electrónica
3                      36.0                     35                Electrónica
4                      34.0                     35                Electrónica
5                       NaN                     67                Electrónica
6                      67.0                     67                Electrónica
7                       NaN                     23                      Hogar
8                      16.0                     23                      Hogar
9                      20.0                     23                      Hogar
10                     34.0                     23                      Hogar

    recencia_dias  F_rank  M_rank  R_rank RFM_Score
0              49     1.0     5.0     1.0       115
1              49     2.0     6.0     2.0       226
2               5     5.0     7.0     5.0       557
3               5     6.0     8.0     6.0       668
4               5     7.0     9.0     7.0       779
5              15     3.0    10.0     3.0      3310
6              15     4.0    11.0     4.0      4411
7               0     8.0     1.0     8.0       881
8               0     9.0     2.0     9.0       992
9               0    10.0     3.0    10.0     10103
10              0    11.0     4.0    11.0     11114

    cliente_id  R_rank  F_rank  M_rank RFM_Score
0            1     1.0     1.0     5.0       115
1            1     2.0     2.0     6.0       226
2            2     5.0     5.0     7.0       557
3            2     6.0     6.0     8.0       668
4            2     7.0     7.0     9.0       779
5            3     3.0     3.0    10.0      3310
6            3     4.0     4.0    11.0      4411
7            4     8.0     8.0     1.0       881
8            4     9.0     9.0     2.0       992
9            4    10.0    10.0     3.0     10103
10           4    11.0    11.0     4.0     11114

Ejercicio 4: Feature Engineering con Texto

In [25]:
df_reviews = pd.DataFrame({
    'review': [
        'Excelente producto! Muy recomendado!!!',
        'Horrible, no funciona',
        'Buena calidad y precio justo',
        'NO LO COMPREN, es una ESTAFA',
        'Me encantó, perfecto para lo que necesitaba :)'
    ],
    'rating': [5, 1, 4, 1, 5]
})

print("--- Reseñas Originales ---")
print(df_reviews)

--- Reseñas Originales ---
                                           review  rating
0          Excelente producto! Muy recomendado!!!       5
1                           Horrible, no funciona       1
2                    Buena calidad y precio justo       4
3                    NO LO COMPREN, es una ESTAFA       1
4  Me encantó, perfecto para lo que necesitaba :)       5

1. Calcular la longitud del texto (en caracteres)

In [31]:
df_reviews['longitud'] = df_reviews['review'].str.len()
print(df_reviews)

                                           review  rating  longitud
0          Excelente producto! Muy recomendado!!!       5        38
1                           Horrible, no funciona       1        21
2                    Buena calidad y precio justo       4        28
3                    NO LO COMPREN, es una ESTAFA       1        28
4  Me encantó, perfecto para lo que necesitaba :)       5        46

2. Contar el número de palabras

In [37]:
df_reviews['palabras'] = df_reviews['review'].str.split().str.len()
print(df_reviews)

                                           review  rating  longitud  palabras
0          Excelente producto! Muy recomendado!!!       5        38         4
1                           Horrible, no funciona       1        21         3
2                    Buena calidad y precio justo       4        28         5
3                    NO LO COMPREN, es una ESTAFA       1        28         6
4  Me encantó, perfecto para lo que necesitaba :)       5        46         8

3. Calcular la longitud promedio de las palabras

In [44]:

df_reviews['promedio_palabras'] = round(df_reviews['longitud'] / df_reviews['palabras'], 2)
print(df_reviews)

                                           review  rating  longitud  palabras  \
0          Excelente producto! Muy recomendado!!!       5        38         4
1                           Horrible, no funciona       1        21         3
2                    Buena calidad y precio justo       4        28         5
3                    NO LO COMPREN, es una ESTAFA       1        28         6
4  Me encantó, perfecto para lo que necesitaba :)       5        46         8

   promedio_palabras
0               9.50
1               7.00
2               5.60
3               4.67
4               5.75

4. Contar el número de signos de exclamación

In [52]:
df_reviews['num_exclamacion'] = df_reviews['review'].str.count("!")
print(df_reviews)

                                           review  rating  longitud  palabras  \
0          Excelente producto! Muy recomendado!!!       5        38         4
1                           Horrible, no funciona       1        21         3
2                    Buena calidad y precio justo       4        28         5
3                    NO LO COMPREN, es una ESTAFA       1        28         6
4  Me encantó, perfecto para lo que necesitaba :)       5        46         8

   promedio_palabras  num_exclamacion
0               9.50                4
1               7.00                0
2               5.60                0
3               4.67                0
4               5.75                0

5. Crear una variable binaria que indique si hay palabras en mayúsculas

In [58]:
df_reviews['dummy_MYUS'] = df_reviews['review'].str.contains(r'[A-Z]', na=False).astype(int)
print(df_reviews)

                                           review  rating  longitud  palabras  \
0          Excelente producto! Muy recomendado!!!       5        38         4
1                           Horrible, no funciona       1        21         3
2                    Buena calidad y precio justo       4        28         5
3                    NO LO COMPREN, es una ESTAFA       1        28         6
4  Me encantó, perfecto para lo que necesitaba :)       5        46         8

   promedio_palabras  num_exclamacion  dummy_MYUS
0               9.50                4           1
1               7.00                0           1
2               5.60                0           1
3               4.67                0           1
4               5.75                0           1

6. Contar el número de emoticones

In [59]:
df_reviews['dummy_emoticonos'] = df_reviews['review'].str.contains(r'[:)]', na=False).astype(int)
print(df_reviews)

                                           review  rating  longitud  palabras  \
0          Excelente producto! Muy recomendado!!!       5        38         4
1                           Horrible, no funciona       1        21         3
2                    Buena calidad y precio justo       4        28         5
3                    NO LO COMPREN, es una ESTAFA       1        28         6
4  Me encantó, perfecto para lo que necesitaba :)       5        46         8

   promedio_palabras  num_exclamacion  dummy_MYUS  dummy_emoticonos
0               9.50                4           1                 0
1               7.00                0           1                 0
2               5.60                0           1                 0
3               4.67                0           1                 0
4               5.75                0           1                 1

7. Calcular el sentimiento (positivo/negativo) basado en palabras clave

In [71]:
negativos_pattern = r'(NO|ESTAFA|Horrible)'

df_reviews['dummy_sentimmiento'] = np.where(df_reviews['review'] .str.contains(negativos_pattern, case=False, na=False), 'negativo', 'positivo')
print(df_reviews)

                                           review  rating  longitud  palabras  \
0          Excelente producto! Muy recomendado!!!       5        38         4
1                           Horrible, no funciona       1        21         3
2                    Buena calidad y precio justo       4        28         5
3                    NO LO COMPREN, es una ESTAFA       1        28         6
4  Me encantó, perfecto para lo que necesitaba :)       5        46         8

   promedio_palabras  num_exclamacion  dummy_MYUS  dummy_emoticonos  \
0               9.50                4           1                 0
1               7.00                0           1                 0
2               5.60                0           1                 0
3               4.67                0           1                 0
4               5.75                0           1                 1

  dummy_sentimmiento
0           positivo
1           negativo
2           positivo
3           negativo
4           positivo

C:\Users\sergi\AppData\Local\Temp\ipykernel_9496\438131356.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_reviews['dummy_sentimmiento'] = np.where(df_reviews['review'] .str.contains(negativos_pattern, case=False, na=False), 'negativo', 'positivo')

8. Crear una variable que indique la intensidad del review (basada en puntuación
y mayúsculas)

In [76]:
df_reviews['intensidad_review(1-10)'] = df_reviews['rating'] * (df_reviews['dummy_MYUS'] + 1)
print(df_reviews)

                                           review  rating  longitud  palabras  \
0          Excelente producto! Muy recomendado!!!       5        38         4
1                           Horrible, no funciona       1        21         3
2                    Buena calidad y precio justo       4        28         5
3                    NO LO COMPREN, es una ESTAFA       1        28         6
4  Me encantó, perfecto para lo que necesitaba :)       5        46         8

   promedio_palabras  num_exclamacion  dummy_MYUS  dummy_emoticonos  \
0               9.50                4           1                 0
1               7.00                0           1                 0
2               5.60                0           1                 0
3               4.67                0           1                 0
4               5.75                0           1                 1

  dummy_sentimmiento  intensidad_review  intensidad_review(1-10)
0           positivo                 10                       10
1           negativo                  2                        2
2           positivo                  8                        8
3           negativo                  2                        2
4           positivo                 10                       10

Ejercicio 5: Pipeline Completo de Feature Engineering

In [79]:
# Semilla para reproducibilidad
np.random.seed(42) 

df_prestamos = pd.DataFrame({
    'cliente_id': range(1, 101),
    'edad': np.random.randint(22, 65, 100),
    'ingreso_anual': np.random.randint(20000, 120000, 100),
    'monto_prestamo': np.random.randint(5000, 50000, 100),
    'plazo_meses': np.random.choice([12, 24, 36, 48, 60], 100),
    'historial_crediticio': np.random.choice(['Excelente', 'Bueno', 'Regular', 'Malo'], 100),
    'num_prestamos_anteriores': np.random.randint(0, 10, 100),
    'fecha_solicitud': pd.date_range('2024-01-01', periods=100, freq='D')
})

print("--- DataFrame de Préstamos (Inicial) ---")
print(df_prestamos)

--- DataFrame de Préstamos (Inicial) ---
    cliente_id  edad  ingreso_anual  monto_prestamo  plazo_meses  \
0            1    60          42662           42505           48
1            2    50          28392            5854           36
2            3    36          50535           29548           36
3            4    64          98603           43623           60
4            5    29          72256           12392           36
..         ...   ...            ...             ...          ...
95          96    26          87172           27399           48
96          97    63         105616           38986           60
97          98    60         113264           25880           24
98          99    62          46736            9735           48
99         100    49         114209           49064           24

   historial_crediticio  num_prestamos_anteriores fecha_solicitud
0                 Bueno                         3      2024-01-01
1               Regular                         7      2024-01-02
2             Excelente                         1      2024-01-03
3                  Malo                         2      2024-01-04
4               Regular                         0      2024-01-05
..                  ...                       ...             ...
95                 Malo                         9      2024-04-05
96              Regular                         0      2024-04-06
97                Bueno                         5      2024-04-07
98            Excelente                         6      2024-04-08
99                 Malo                         7      2024-04-09

[100 rows x 8 columns]

1. Ratios financieros relevantes

In [96]:
df_prestamos['ratio_endeudamiento'] = df_prestamos['monto_prestamo'] / df_prestamos['ingreso_anual']
df_prestamos['pago_mensual'] = round(df_prestamos['monto_prestamo'] / df_prestamos['plazo_meses'], 2)
df_prestamos['pago_vs_ingreso'] = df_prestamos['pago_mensual'] / (df_prestamos['ingreso_anual'] / 12)
print(df_prestamos)
display(df_prestamos[['cliente_id', 'ratio_endeudamiento', 'pago_mensual', 'pago_vs_ingreso']])

    cliente_id  edad  ingreso_anual  monto_prestamo  plazo_meses  \
0            1    60          42662           42505           48
1            2    50          28392            5854           36
2            3    36          50535           29548           36
3            4    64          98603           43623           60
4            5    29          72256           12392           36
..         ...   ...            ...             ...          ...
95          96    26          87172           27399           48
96          97    63         105616           38986           60
97          98    60         113264           25880           24
98          99    62          46736            9735           48
99         100    49         114209           49064           24

   historial_crediticio  num_prestamos_anteriores fecha_solicitud  \
0                 Bueno                         3      2024-01-01
1               Regular                         7      2024-01-02
2             Excelente                         1      2024-01-03
3                  Malo                         2      2024-01-04
4               Regular                         0      2024-01-05
..                  ...                       ...             ...
95                 Malo                         9      2024-04-05
96              Regular                         0      2024-04-06
97                Bueno                         5      2024-04-07
98            Excelente                         6      2024-04-08
99                 Malo                         7      2024-04-09

    ratio_endeudamiento  pago_mensual  pago_vs_ingreso
0              0.996320        885.52         0.249080
1              0.206185        162.61         0.068728
2              0.584704        820.78         0.194902
3              0.442410        727.05         0.088482
4              0.171501        344.22         0.057167
..                  ...           ...              ...
95             0.314310        570.81         0.078577
96             0.369130        649.77         0.073826
97             0.228493       1078.33         0.114246
98             0.208298        202.81         0.052074
99             0.429598       2044.33         0.214799

[100 rows x 11 columns]

    cliente_id  ratio_endeudamiento  pago_mensual  pago_vs_ingreso
0            1             0.996320        885.52         0.249080
1            2             0.206185        162.61         0.068728
2            3             0.584704        820.78         0.194902
3            4             0.442410        727.05         0.088482
4            5             0.171501        344.22         0.057167
..         ...                  ...           ...              ...
95          96             0.314310        570.81         0.078577
96          97             0.369130        649.77         0.073826
97          98             0.228493       1078.33         0.114246
98          99             0.208298        202.81         0.052074
99         100             0.429598       2044.33         0.214799

[100 rows x 4 columns]

2. Características temporales

In [104]:
df_prestamos['dia_solicitud'] = df_prestamos['fecha_solicitud'].dt.day_name()
df_prestamos['mes_solicitud'] = df_prestamos['fecha_solicitud'].dt.month
df_prestamos['es_fin_de_semana'] = np.where(df_prestamos['fecha_solicitud'].dt.dayofweek >= 5, 1, 0)

print(df_prestamos)

    cliente_id  edad  ingreso_anual  monto_prestamo  plazo_meses  \
0            1    60          42662           42505           48
1            2    50          28392            5854           36
2            3    36          50535           29548           36
3            4    64          98603           43623           60
4            5    29          72256           12392           36
..         ...   ...            ...             ...          ...
95          96    26          87172           27399           48
96          97    63         105616           38986           60
97          98    60         113264           25880           24
98          99    62          46736            9735           48
99         100    49         114209           49064           24

   historial_crediticio  num_prestamos_anteriores fecha_solicitud  \
0                 Bueno                         3      2024-01-01
1               Regular                         7      2024-01-02
2             Excelente                         1      2024-01-03
3                  Malo                         2      2024-01-04
4               Regular                         0      2024-01-05
..                  ...                       ...             ...
95                 Malo                         9      2024-04-05
96              Regular                         0      2024-04-06
97                Bueno                         5      2024-04-07
98            Excelente                         6      2024-04-08
99                 Malo                         7      2024-04-09

    ratio_endeudamiento  pago_mensual  ...  score_historial historial_Bueno  \
0              0.996320        885.52  ...                3               1
1              0.206185        162.61  ...                2               0
2              0.584704        820.78  ...                4               0
3              0.442410        727.05  ...                1               0
4              0.171501        344.22  ...                2               0
..                  ...           ...  ...              ...             ...
95             0.314310        570.81  ...                1               0
96             0.369130        649.77  ...                2               0
97             0.228493       1078.33  ...                3               1
98             0.208298        202.81  ...                4               0
99             0.429598       2044.33  ...                1               0

    historial_Excelente  historial_Malo  historial_Regular      rango_edad  \
0                     0               0                  0  Senior_Estable
1                     0               0                  1  Senior_Estable
2                     1               0                  0      Edad_Media
3                     0               1                  0  Senior_Estable
4                     0               0                  1    Joven_Riesgo
..                  ...             ...                ...             ...
95                    0               1                  0    Joven_Riesgo
96                    0               0                  1  Senior_Estable
97                    0               0                  0  Senior_Estable
98                    1               0                  0  Senior_Estable
99                    0               1                  0      Edad_Media

    rango_plazo  rango_ingreso_pct  ingreso_por_edad monto_por_prestamo_previo
0   Largo_Plazo                 Q1        711.033333              10626.250000
1   Largo_Plazo                 Q1        567.840000                731.750000
2   Largo_Plazo                 Q2       1403.750000              14774.000000
3   Largo_Plazo                 Q4       1540.671875              14541.000000
4   Largo_Plazo                 Q3       2491.586207              12392.000000
..          ...                ...               ...                       ...
95  Largo_Plazo                 Q4       3352.769231               2739.900000
96  Largo_Plazo                 Q4       1676.444444              38986.000000
97  Corto_Plazo                 Q5       1887.733333               4313.333333
98  Largo_Plazo                 Q2        753.806452               1390.714286
99  Corto_Plazo                 Q5       2330.795918               6133.000000

[100 rows x 24 columns]

3. Codificación de variables categóricas

In [105]:
historial_mapping = {'Malo': 1, 'Regular': 2, 'Bueno': 3, 'Excelente': 4}
df_prestamos['score_historial'] = df_prestamos['historial_crediticio'].map(historial_mapping)
df_dummies = pd.get_dummies(df_prestamos['historial_crediticio'], prefix='historial').astype(int)
df_prestamos = pd.concat([df_prestamos, df_dummies], axis=1)

print(df_prestamos)

    cliente_id  edad  ingreso_anual  monto_prestamo  plazo_meses  \
0            1    60          42662           42505           48
1            2    50          28392            5854           36
2            3    36          50535           29548           36
3            4    64          98603           43623           60
4            5    29          72256           12392           36
..         ...   ...            ...             ...          ...
95          96    26          87172           27399           48
96          97    63         105616           38986           60
97          98    60         113264           25880           24
98          99    62          46736            9735           48
99         100    49         114209           49064           24

   historial_crediticio  num_prestamos_anteriores fecha_solicitud  \
0                 Bueno                         3      2024-01-01
1               Regular                         7      2024-01-02
2             Excelente                         1      2024-01-03
3                  Malo                         2      2024-01-04
4               Regular                         0      2024-01-05
..                  ...                       ...             ...
95                 Malo                         9      2024-04-05
96              Regular                         0      2024-04-06
97                Bueno                         5      2024-04-07
98            Excelente                         6      2024-04-08
99                 Malo                         7      2024-04-09

    ratio_endeudamiento  pago_mensual  ... historial_Regular      rango_edad  \
0              0.996320        885.52  ...                 0  Senior_Estable
1              0.206185        162.61  ...                 1  Senior_Estable
2              0.584704        820.78  ...                 0      Edad_Media
3              0.442410        727.05  ...                 0  Senior_Estable
4              0.171501        344.22  ...                 1    Joven_Riesgo
..                  ...           ...  ...               ...             ...
95             0.314310        570.81  ...                 0    Joven_Riesgo
96             0.369130        649.77  ...                 1  Senior_Estable
97             0.228493       1078.33  ...                 0  Senior_Estable
98             0.208298        202.81  ...                 0  Senior_Estable
99             0.429598       2044.33  ...                 0      Edad_Media

    rango_plazo  rango_ingreso_pct  ingreso_por_edad  \
0   Largo_Plazo                 Q1        711.033333
1   Largo_Plazo                 Q1        567.840000
2   Largo_Plazo                 Q2       1403.750000
3   Largo_Plazo                 Q4       1540.671875
4   Largo_Plazo                 Q3       2491.586207
..          ...                ...               ...
95  Largo_Plazo                 Q4       3352.769231
96  Largo_Plazo                 Q4       1676.444444
97  Corto_Plazo                 Q5       1887.733333
98  Largo_Plazo                 Q2        753.806452
99  Corto_Plazo                 Q5       2330.795918

    monto_por_prestamo_previo  historial_Bueno  historial_Excelente  \
0                10626.250000                1                    0
1                  731.750000                0                    0
2                14774.000000                0                    1
3                14541.000000                0                    0
4                12392.000000                0                    0
..                        ...              ...                  ...
95                2739.900000                0                    0
96               38986.000000                0                    0
97                4313.333333                1                    0
98                1390.714286                0                    1
99                6133.000000                0                    0

    historial_Malo historial_Regular
0                0                 0
1                0                 1
2                0                 0
3                1                 0
4                0                 1
..             ...               ...
95               1                 0
96               0                 1
97               0                 0
98               0                 0
99               1                 0

[100 rows x 28 columns]


4. Binning de variables continuas

In [106]:
bins_edad = [20, 35, 50, 70] # Jóvenes, Media, Senior
labels_edad = ['Joven_Riesgo', 'Edad_Media', 'Senior_Estable']
df_prestamos['rango_edad'] = pd.cut(df_prestamos['edad'], bins=bins_edad, labels=labels_edad, right=False)
bins_plazo = [0, 36, 61] # Corto (36 meses o menos) o Largo (más de 36)
labels_plazo = ['Corto_Plazo', 'Largo_Plazo']
df_prestamos['rango_plazo'] = pd.cut(df_prestamos['plazo_meses'], bins=bins_plazo, labels=labels_plazo, right=False)
df_prestamos['rango_ingreso_pct'] = pd.qcut(
    df_prestamos['ingreso_anual'], q=5, labels=['Q1', 'Q2', 'Q3', 'Q4', 'Q5'], duplicates='drop'
)

print(df_prestamos)

    cliente_id  edad  ingreso_anual  monto_prestamo  plazo_meses  \
0            1    60          42662           42505           48
1            2    50          28392            5854           36
2            3    36          50535           29548           36
3            4    64          98603           43623           60
4            5    29          72256           12392           36
..         ...   ...            ...             ...          ...
95          96    26          87172           27399           48
96          97    63         105616           38986           60
97          98    60         113264           25880           24
98          99    62          46736            9735           48
99         100    49         114209           49064           24

   historial_crediticio  num_prestamos_anteriores fecha_solicitud  \
0                 Bueno                         3      2024-01-01
1               Regular                         7      2024-01-02
2             Excelente                         1      2024-01-03
3                  Malo                         2      2024-01-04
4               Regular                         0      2024-01-05
..                  ...                       ...             ...
95                 Malo                         9      2024-04-05
96              Regular                         0      2024-04-06
97                Bueno                         5      2024-04-07
98            Excelente                         6      2024-04-08
99                 Malo                         7      2024-04-09

    ratio_endeudamiento  pago_mensual  ... historial_Regular      rango_edad  \
0              0.996320        885.52  ...                 0  Senior_Estable
1              0.206185        162.61  ...                 1  Senior_Estable
2              0.584704        820.78  ...                 0      Edad_Media
3              0.442410        727.05  ...                 0  Senior_Estable
4              0.171501        344.22  ...                 1    Joven_Riesgo
..                  ...           ...  ...               ...             ...
95             0.314310        570.81  ...                 0    Joven_Riesgo
96             0.369130        649.77  ...                 1  Senior_Estable
97             0.228493       1078.33  ...                 0  Senior_Estable
98             0.208298        202.81  ...                 0  Senior_Estable
99             0.429598       2044.33  ...                 0      Edad_Media

    rango_plazo  rango_ingreso_pct  ingreso_por_edad  \
0   Largo_Plazo                 Q1        711.033333
1   Largo_Plazo                 Q1        567.840000
2   Largo_Plazo                 Q2       1403.750000
3   Largo_Plazo                 Q4       1540.671875
4   Largo_Plazo                 Q3       2491.586207
..          ...                ...               ...
95  Largo_Plazo                 Q4       3352.769231
96  Largo_Plazo                 Q4       1676.444444
97  Corto_Plazo                 Q5       1887.733333
98  Largo_Plazo                 Q2        753.806452
99  Corto_Plazo                 Q5       2330.795918

    monto_por_prestamo_previo  historial_Bueno  historial_Excelente  \
0                10626.250000                1                    0
1                  731.750000                0                    0
2                14774.000000                0                    1
3                14541.000000                0                    0
4                12392.000000                0                    0
..                        ...              ...                  ...
95                2739.900000                0                    0
96               38986.000000                0                    0
97                4313.333333                1                    0
98                1390.714286                0                    1
99                6133.000000                0                    0

    historial_Malo historial_Regular
0                0                 0
1                0                 1
2                0                 0
3                1                 0
4                0                 1
..             ...               ...
95               1                 0
96               0                 1
97               0                 0
98               0                 0
99               1                 0

[100 rows x 28 columns]

5. Interacciones entre variables

In [107]:
df_prestamos['ingreso_por_edad'] = df_prestamos['ingreso_anual'] / df_prestamos['edad']
df_prestamos['monto_por_prestamo_previo'] = df_prestamos['monto_prestamo'] / (df_prestamos['num_prestamos_anteriores'] + 1) # +1 para evitar la división por cero

print(df_prestamos)

    cliente_id  edad  ingreso_anual  monto_prestamo  plazo_meses  \
0            1    60          42662           42505           48
1            2    50          28392            5854           36
2            3    36          50535           29548           36
3            4    64          98603           43623           60
4            5    29          72256           12392           36
..         ...   ...            ...             ...          ...
95          96    26          87172           27399           48
96          97    63         105616           38986           60
97          98    60         113264           25880           24
98          99    62          46736            9735           48
99         100    49         114209           49064           24

   historial_crediticio  num_prestamos_anteriores fecha_solicitud  \
0                 Bueno                         3      2024-01-01
1               Regular                         7      2024-01-02
2             Excelente                         1      2024-01-03
3                  Malo                         2      2024-01-04
4               Regular                         0      2024-01-05
..                  ...                       ...             ...
95                 Malo                         9      2024-04-05
96              Regular                         0      2024-04-06
97                Bueno                         5      2024-04-07
98            Excelente                         6      2024-04-08
99                 Malo                         7      2024-04-09

    ratio_endeudamiento  pago_mensual  ... historial_Regular      rango_edad  \
0              0.996320        885.52  ...                 0  Senior_Estable
1              0.206185        162.61  ...                 1  Senior_Estable
2              0.584704        820.78  ...                 0      Edad_Media
3              0.442410        727.05  ...                 0  Senior_Estable
4              0.171501        344.22  ...                 1    Joven_Riesgo
..                  ...           ...  ...               ...             ...
95             0.314310        570.81  ...                 0    Joven_Riesgo
96             0.369130        649.77  ...                 1  Senior_Estable
97             0.228493       1078.33  ...                 0  Senior_Estable
98             0.208298        202.81  ...                 0  Senior_Estable
99             0.429598       2044.33  ...                 0      Edad_Media

    rango_plazo  rango_ingreso_pct  ingreso_por_edad  \
0   Largo_Plazo                 Q1        711.033333
1   Largo_Plazo                 Q1        567.840000
2   Largo_Plazo                 Q2       1403.750000
3   Largo_Plazo                 Q4       1540.671875
4   Largo_Plazo                 Q3       2491.586207
..          ...                ...               ...
95  Largo_Plazo                 Q4       3352.769231
96  Largo_Plazo                 Q4       1676.444444
97  Corto_Plazo                 Q5       1887.733333
98  Largo_Plazo                 Q2        753.806452
99  Corto_Plazo                 Q5       2330.795918

    monto_por_prestamo_previo  historial_Bueno  historial_Excelente  \
0                10626.250000                1                    0
1                  731.750000                0                    0
2                14774.000000                0                    1
3                14541.000000                0                    0
4                12392.000000                0                    0
..                        ...              ...                  ...
95                2739.900000                0                    0
96               38986.000000                0                    0
97                4313.333333                1                    0
98                1390.714286                0                    1
99                6133.000000                0                    0

    historial_Malo historial_Regular
0                0                 0
1                0                 1
2                0                 0
3                1                 0
4                0                 1
..             ...               ...
95               1                 0
96               0                 1
97               0                 0
98               0                 0
99               1                 0

[100 rows x 28 columns]


6. Agregaciones relevantes

In [108]:
df_prestamos['riesgo_mora_score'] = df_prestamos['score_historial'] * df_prestamos['num_prestamos_anteriores']
df_prestamos['dias_desde_max_fecha'] = (df_prestamos['fecha_solicitud'].max() - df_prestamos['fecha_solicitud']).dt.days

print(df_prestamos)

    cliente_id  edad  ingreso_anual  monto_prestamo  plazo_meses  \
0            1    60          42662           42505           48
1            2    50          28392            5854           36
2            3    36          50535           29548           36
3            4    64          98603           43623           60
4            5    29          72256           12392           36
..         ...   ...            ...             ...          ...
95          96    26          87172           27399           48
96          97    63         105616           38986           60
97          98    60         113264           25880           24
98          99    62          46736            9735           48
99         100    49         114209           49064           24

   historial_crediticio  num_prestamos_anteriores fecha_solicitud  \
0                 Bueno                         3      2024-01-01
1               Regular                         7      2024-01-02
2             Excelente                         1      2024-01-03
3                  Malo                         2      2024-01-04
4               Regular                         0      2024-01-05
..                  ...                       ...             ...
95                 Malo                         9      2024-04-05
96              Regular                         0      2024-04-06
97                Bueno                         5      2024-04-07
98            Excelente                         6      2024-04-08
99                 Malo                         7      2024-04-09

    ratio_endeudamiento  pago_mensual  ...  rango_plazo rango_ingreso_pct  \
0              0.996320        885.52  ...  Largo_Plazo                Q1
1              0.206185        162.61  ...  Largo_Plazo                Q1
2              0.584704        820.78  ...  Largo_Plazo                Q2
3              0.442410        727.05  ...  Largo_Plazo                Q4
4              0.171501        344.22  ...  Largo_Plazo                Q3
..                  ...           ...  ...          ...               ...
95             0.314310        570.81  ...  Largo_Plazo                Q4
96             0.369130        649.77  ...  Largo_Plazo                Q4
97             0.228493       1078.33  ...  Corto_Plazo                Q5
98             0.208298        202.81  ...  Largo_Plazo                Q2
99             0.429598       2044.33  ...  Corto_Plazo                Q5

    ingreso_por_edad  monto_por_prestamo_previo  historial_Bueno  \
0         711.033333               10626.250000                1
1         567.840000                 731.750000                0
2        1403.750000               14774.000000                0
3        1540.671875               14541.000000                0
4        2491.586207               12392.000000                0
..               ...                        ...              ...
95       3352.769231                2739.900000                0
96       1676.444444               38986.000000                0
97       1887.733333                4313.333333                1
98        753.806452                1390.714286                0
99       2330.795918                6133.000000                0

    historial_Excelente  historial_Malo  historial_Regular  riesgo_mora_score  \
0                     0               0                  0                  9
1                     0               0                  1                 14
2                     1               0                  0                  4
3                     0               1                  0                  2
4                     0               0                  1                  0
..                  ...             ...                ...                ...
95                    0               1                  0                  9
96                    0               0                  1                  0
97                    0               0                  0                 15
98                    1               0                  0                 24
99                    0               1                  0                  7

   dias_desde_max_fecha
0                    99
1                    98
2                    97
3                    96
4                    95
..                  ...
95                    4
96                    3
97                    2
98                    1
99                    0

[100 rows x 30 columns]