What are we going to learn today?
In this article, we will learn how to remove /edit missing and incorrect values in a data set. This process is considered part of data cleaning.

In Pandas, missing values are called null values (NumPy Not a Number-NaN). Incorrect values can be anything that must be removed or edited for practical data analysis.

NumPy is an advanced mathematical functions library, and we will use it for creating null values in pandas np.nan, which will convert into NaN.

Why is it important to learn?
The majority of the time, data scientists are busy with data cleaning. Because, in the real world, data is not what we want it to be. Real-world data is noisy, which affects the accuracy of our analysis and machine learning models. We will learn more about machine learning later, but here is a quick overview of why data cleaning helps with machine learning.

Machine learning models perform very poorly on noisy and uncleaned data. The poor model means it leads to underfitting and overfitting.

Machine learning models are algorithms that train over a set of data to recognize certain types of patterns or make predictions.
Underfitting means the machine learning model neither performs well on training nor test data.
Overfitting is when a machine learning model performs well on training data but poor on testing data.
How are we going to achieve today’s learning goal?
Plan for today is:

Handling null values
Dealing with custom missing values
Filling in missing data

In [1]:
import pandas as pd
import numpy as np

We will create a custom dataset with missing values — NaN and None. The np.nan (NaN) and None values are null values in pandas.

Apart from np.nan and None, we will add some incorrect data with string values like (‘NaN’, ‘None’, ‘?’). It will seem like null values in the data frame, but these are actually strings.

Let’s start by creating a dictionary as the basis for our data frame.

In [3]:
student = {
'first': ['Fatima', 'Carine', 'Alla', 'Salman', np.nan, None, 'NA'],
'last': ['Khan', 'Aries', 'Ben', 'Malik', np.nan, np.nan, 'NaN'],
'email': ['fatimakhan@gmail.com', 'caries@email.com', 'allaben@email.com', None, np.nan, 'saqib@gmail.com', 'NA'],
'age': [33, 55, 63, 36, np.nan, None, '?']
}
student

{'first': ['Fatima', 'Carine', 'Alla', 'Salman', nan, None, 'NA'],
 'last': ['Khan', 'Aries', 'Ben', 'Malik', nan, nan, 'NaN'],
 'email': ['fatimakhan@gmail.com',
  'caries@email.com',
  'allaben@email.com',
  None,
  nan,
  'saqib@gmail.com',
  'NA'],
 'age': [33, 55, 63, 36, nan, None, '?']}

Converting the dictionary into a data frame and display it.

In [4]:
data = pd.DataFrame(student)
data

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com    33
1  Carine  Aries      caries@email.com    55
2    Alla    Ben     allaben@email.com    63
3  Salman  Malik                  None    36
4     NaN    NaN                   NaN   NaN
5    None    NaN       saqib@gmail.com  None
6      NA    NaN                    NA     ?

Handling null values
First, we will check if there are any null values in the data set with the isnull() method. It returns a boolean operator True where it finds a null value; otherwise, it returns False.

In [5]:
data.isnull()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6  False  False  False  False

If we want to count the number of null values, we will sum it with the sum() method.

In [6]:
data.isnull().sum()

first    2
last     2
email    2
age      2
dtype: int64

We can see several null values in the data frame. To remove null values, we will be using dropna() method. dropna(): It removes missing values from the data set. Important parameters in this method are:

axis: It removes null values from either rows or columns. axis = 0 or index means rows and axis = 1 or columns means columns.

how: Using this, we describe how to remove null values. If how is set to any, it means drop that row or column where at least one null value. If how is set to all, it drops the row and column where all values are null. By default, how is set to rows.

inplace: It takes boolean operators. If it is True, we want to make a permanent change in the original data frame. If it is False, it only shows the result of the dropna() method without making any changes to the data set.

In [7]:
data.dropna(how='any')

    first   last                 email age
0  Fatima   Khan  fatimakhan@gmail.com  33
1  Carine  Aries      caries@email.com  55
2    Alla    Ben     allaben@email.com  63
6      NA    NaN                    NA   ?

Let’s change the axis, and Now we will remove by columns.

In [8]:
data.dropna(how='any', axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

Now let’s try a combination of all and axis set to 1

In [9]:
data.dropna(how='all', axis=1)

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com    33
1  Carine  Aries      caries@email.com    55
2    Alla    Ben     allaben@email.com    63
3  Salman  Malik                  None    36
4     NaN    NaN                   NaN   NaN
5    None    NaN       saqib@gmail.com  None
6      NA    NaN                    NA     ?

The result shows the full data frame as no column has all null values.

Now let’s try all and the axis will be set to rows by default.

In [10]:
data.dropna(how='any')

    first   last                 email age
0  Fatima   Khan  fatimakhan@gmail.com  33
1  Carine  Aries      caries@email.com  55
2    Alla    Ben     allaben@email.com  63
6      NA    NaN                    NA   ?

Let’s review the output. Interestingly row 6 is still present while row 4 is gone. This is because row 6 has fake null values :). These are strings and not real null values.

On to the next section to learn more about custom null values aka fake null values.

Dealing with custom missing values
Here we are using the NaN values and set the inplace parameter True — row 6 has custom missing values, and we will change them into real missing values.

In [11]:
data.replace({'NA':np.nan, 'NaN':np.nan, '?':np.nan}, inplace=True)

C:\Users\sergi\AppData\Local\Temp\ipykernel_8144\2631578731.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({'NA':np.nan, 'NaN':np.nan, '?':np.nan}, inplace=True)

Let’s execute the dropna() method now to drop all rows with null values including row 6.

In [12]:
data.dropna()

    first   last                 email   age
0  Fatima   Khan  fatimakhan@gmail.com  33.0
1  Carine  Aries      caries@email.com  55.0
2    Alla    Ben     allaben@email.com  63.0

Let’s execute the dropna() method now to drop all rows with null values including row 6.

Filling in missing data
Sometimes removing missing values is not effective as we might lose important information. It can affect our machine learning model’s performance as well. So instead of removing, we fill missing numerical values with central tendency values (mean, median and mode). To fill missing values, we used the fillna() method.

The fillna() method replaces the missing values with a specified value. It also takes a few parameters:

inplace: Changes in the original data frame.

axis: Axis along which to fill missing values.

For example, we will add a MISSING string in the data frame without mentioning an axis. It will fill all the missing values with MISSING.

In [13]:
data.fillna('MISSING')

     first     last                 email      age
0   Fatima     Khan  fatimakhan@gmail.com     33.0
1   Carine    Aries      caries@email.com     55.0
2     Alla      Ben     allaben@email.com     63.0
3   Salman    Malik               MISSING     36.0
4  MISSING  MISSING               MISSING  MISSING
5  MISSING  MISSING       saqib@gmail.com  MISSING
6  MISSING  MISSING               MISSING  MISSING

Now let’s fill the MISSING values in the age column with the mean of the columns instead of removing the MISSING values.

In [14]:
data['age'].fillna(data['age'].mean(), inplace=True)
data

C:\Users\sergi\AppData\Local\Temp\ipykernel_8144\4210354984.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['age'].fillna(data['age'].mean(), inplace=True)

    first   last                 email    age
0  Fatima   Khan  fatimakhan@gmail.com  33.00
1  Carine  Aries      caries@email.com  55.00
2    Alla    Ben     allaben@email.com  63.00
3  Salman  Malik                  None  36.00
4     NaN    NaN                   NaN  46.75
5    None    NaN       saqib@gmail.com  46.75
6     NaN    NaN                   NaN  46.75

Now, let’s see the output, and we can see that the age column MISSING values are filled by its mean.